import type { OrientationChapter } from './index.js';

export function getChapter04(): OrientationChapter {
  return {
    id: 'ch04-walls-gates',
    number: 4,
    title: 'Walls and Gates',
    subtitle: 'Authentication, Access Control, and Defense Mechanisms',
    clearanceLevel: 'LEVEL 1 — RESTRICTED',
    tier: 2,
    estimatedMinutes: 25,
    sections: [
      {
        id: 'auth-fundamentals',
        title: 'Authentication Fundamentals',
        steps: [
          {
            type: 'narrative',
            speaker: 'DIRECTOR VASQUEZ',
            lines: [
              'Observer.',
              '',
              'Your Handler tells me you completed Tier 1 adequately.',
              'You now have Level 1 clearance. The material ahead is',
              'more demanding. Tier 2 covers defensive operations —',
              'the mechanisms that protect systems and the ways those',
              'mechanisms fail.',
              '',
              'Pay attention. This is where theory becomes tradecraft.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Authentication is how a system verifies you are who you',
              'claim to be. It rests on three factors:',
              '',
              '  SOMETHING YOU KNOW  — passwords, PINs, security questions',
              '  SOMETHING YOU HAVE  — hardware tokens, phones, smart cards',
              '  SOMETHING YOU ARE   — fingerprints, face, retina, voice',
              '',
              'Single-factor authentication uses one. Multi-factor (MFA)',
              'combines two or more. The principle: even if one factor is',
              'compromised, the attacker still lacks the others.',
              '',
              'In practice, most breaches start with compromised passwords.',
              'MFA is the single most effective control against credential',
              'theft — and it\'s still not universally deployed.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Why passwords fail. This matters because you\'ll see these',
              'failures in every investigation you run.',
              '',
              '  WEAK PASSWORDS     — "Password123", "company2026"',
              '                       Crackable in seconds with wordlists',
              '',
              '  PASSWORD REUSE     — Same password across personal and',
              '                       corporate accounts. One breach on a',
              '                       third-party site = access to your network',
              '',
              '  CREDENTIAL STUFFING — Automated login attempts using',
              '                        username/password pairs from data breaches',
              '                        Billions of leaked credentials exist',
              '',
              '  PHISHING           — You\'ve already seen this in Chapter 3.',
              '                       Fake login pages harvest credentials',
              '',
              '  INSECURE STORAGE   — Passwords stored in plaintext or with',
              '                       weak hashing (MD5, SHA1 without salt)',
              '                       One database breach = all passwords exposed',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Secure password storage is non-negotiable. The standard:',
              '',
              '  bcrypt, scrypt, or argon2 — purpose-built password hashing',
              '  functions. They\'re intentionally slow, making brute-force',
              '  cracking computationally expensive.',
              '',
              '  SALTING — A random value appended to each password before',
              '  hashing. Even if two users have the same password, their',
              '  hashes are different. Prevents rainbow table attacks.',
              '',
              '  PEPPERING — A secret key applied server-side in addition',
              '  to the salt. Even if the database is stolen, the hashes',
              '  can\'t be cracked without the pepper.',
              '',
              'If you see MD5 or SHA1 password hashes in an investigation,',
              'that system was already compromised by design.',
            ],
          },
          {
            type: 'quiz',
            speaker: 'HANDLER',
            lines: [
              'An investigation reveals a database dump with the following',
              'password storage format:',
              '',
              '  user: admin',
              '  password: 5f4dcc3b5aa765d61d8327deb882cf99',
              '',
              'That hash is 32 hex characters.',
            ],
            question: 'What is the vulnerability in this password storage?',
            options: [
              { id: 'md5', text: 'MD5 hash — unsalted, fast to crack, no modern defenses', correct: true },
              { id: 'aes', text: 'AES encryption — the password can be decrypted', correct: false },
              { id: 'bcrypt', text: 'bcrypt with low cost factor', correct: false },
              { id: 'base64', text: 'Base64 encoding — not hashing at all', correct: false },
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Correct. That\'s MD5 — 32 hex characters, no salt visible.',
              'The string "password" hashes to exactly that value in MD5.',
              'Any attacker with a rainbow table identifies it instantly.',
              '',
              'MFA types you\'ll encounter in the field:',
              '',
              '  TOTP (Time-based One-Time Password)',
              '    Apps like Google Authenticator generate 6-digit codes',
              '    that rotate every 30 seconds. Based on a shared secret.',
              '    Phishable if the attacker proxies the login in real-time.',
              '',
              '  HARDWARE KEYS (FIDO2/WebAuthn)',
              '    YubiKey, Titan Key. Cryptographic challenge-response.',
              '    NOT phishable — the key verifies the domain is legitimate.',
              '    The gold standard for authentication security.',
              '',
              '  PUSH NOTIFICATIONS',
              '    "Approve this login?" sent to your phone. Convenient but',
              '    vulnerable to MFA fatigue attacks — the attacker spams',
              '    push requests until the user approves one to make it stop.',
            ],
          },
          {
            type: 'quiz',
            speaker: 'HANDLER',
            lines: [
              'A company is experiencing repeated unauthorized access despite',
              'having MFA enabled. Their MFA solution sends push notifications',
              'to employees\' phones. Users report receiving 20-30 push',
              'requests in rapid succession during off-hours.',
            ],
            question: 'What attack is being used to bypass their MFA?',
            options: [
              { id: 'fatigue', text: 'MFA fatigue / push bombing — overwhelming users until they approve', correct: true },
              { id: 'sim', text: 'SIM swapping — intercepting SMS codes', correct: false },
              { id: 'phish', text: 'Real-time phishing proxy (evilginx)', correct: false },
            ],
          },
        ],
      },
      {
        id: 'session-management',
        title: 'Session Management',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Authentication happens once. After that, the system needs',
              'to remember you\'re authenticated. That\'s session management.',
              '',
              'When you log in, the server creates a session and gives you',
              'a session token — a random string stored in a cookie or',
              'header. Every subsequent request includes that token to',
              'prove you\'re the same authenticated user.',
              '',
              'If an attacker steals your session token, they become you.',
              'No password needed. No MFA needed. They have your session.',
              '',
              'This is why OAuth token theft (like you saw in Chapter 3)',
              'is so dangerous. The phishing page didn\'t need the victim\'s',
              'password permanently — it needed their OAuth token.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Session vulnerabilities to watch for:',
              '',
              '  PREDICTABLE TOKENS — Sequential IDs, timestamps,',
              '    or patterns that let an attacker guess valid tokens.',
              '    Secure tokens must be cryptographically random.',
              '',
              '  SESSION FIXATION — Attacker sets the victim\'s session',
              '    ID before they log in. The victim authenticates, and',
              '    the attacker already has the session token.',
              '',
              '  SESSION HIJACKING — Intercepting tokens via network',
              '    sniffing (if not using HTTPS), XSS attacks, or',
              '    accessing tokens in logs/URLs.',
              '',
              '  INSUFFICIENT EXPIRATION — Tokens that never expire or',
              '    have overly long lifetimes. If stolen, the attacker',
              '    has access indefinitely.',
              '',
              '  FAILURE TO INVALIDATE — When a user changes their',
              '    password, old sessions should be killed. Many systems',
              '    don\'t do this — the attacker\'s stolen token survives.',
            ],
          },
          {
            type: 'guided-command',
            speaker: 'HANDLER',
            expectedCommand: 'tokens --user=m.hargrove',
            commandPatterns: ['tokens --user=m.hargrove', 'tokens --user=hargrove', 'tokens --user m.hargrove'],
            lines: [
              'Let me show you what session tokens look like in practice.',
              'Examine the active tokens for a compromised account.',
            ],
            commandOutput: `═══ ACTIVE TOKENS: m.hargrove@hm-law.com ═══════════════

Token ID       Type      Scope                    Created          Expires          Source IP
─────────────────────────────────────────────────────────────────────────────────────────
TK-8891        OAuth2    mail.read,drive.readonly  2026-04-01 06:22  2026-04-08 06:22  198.51.100.88  !! EXTERNAL !!
TK-8834        OAuth2    mail.read,calendar.read   2026-03-28 09:15  2026-04-04 09:15  10.10.5.20
TK-8790        Session   full_access               2026-03-25 08:00  2026-04-01 08:00  10.10.5.20     EXPIRED
TK-8745        OAuth2    mail.send                  2026-03-20 14:30  never             10.10.5.20     !! NO EXPIRY !!

!! Token TK-8891 granted from known attacker IP !!
!! Token TK-8745 has no expiration — persistent access if stolen !!`,
            explanation: [
              'Four tokens. Two red flags:',
              '',
              'TK-8891 — Created from the attacker\'s IP (198.51.100.88)',
              'with mail and drive access. This is the phished OAuth token.',
              'Expires in 7 days — the attacker has a week of access.',
              '',
              'TK-8745 — No expiration. This OAuth token was granted',
              'months ago and never expires. If this token were stolen,',
              'the attacker would have permanent email send access.',
              '"never" expiry tokens are a security design failure.',
              '',
              'Remediation: revoke TK-8891 immediately (attacker token),',
              'and flag TK-8745 for policy review (no-expiry tokens',
              'should not exist in a secure environment).',
            ],
            hintOnWrong: 'Type: tokens --user=m.hargrove',
          },
        ],
      },
      {
        id: 'access-control',
        title: 'Access Control Models',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Authentication answers "who are you?"',
              'Access control answers "what are you allowed to do?"',
              '',
              'Four models you need to know:',
              '',
              '  DAC (Discretionary Access Control)',
              '    The resource owner decides who gets access.',
              '    Example: file permissions on your laptop.',
              '    Weakness: users can grant access to anyone,',
              '    including people who shouldn\'t have it.',
              '',
              '  MAC (Mandatory Access Control)',
              '    The system enforces access based on classification',
              '    levels. Users CAN\'T override it.',
              '    Example: military clearance levels (TOP SECRET,',
              '    SECRET, CONFIDENTIAL). A SECRET-cleared user',
              '    cannot access TOP SECRET material regardless of role.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              '  RBAC (Role-Based Access Control)',
              '    Access is granted based on your role, not your identity.',
              '    Example: "Accountant" role can access financial systems.',
              '    "Engineer" role can access code repositories.',
              '    Most common model in corporate environments.',
              '    Weakness: role explosion — over time, too many roles',
              '    are created, and users accumulate permissions they',
              '    no longer need.',
              '',
              '  ABAC (Attribute-Based Access Control)',
              '    Access decisions based on attributes: user role,',
              '    time of day, location, device type, data classification.',
              '    Example: "Engineers can access code repos from corporate',
              '    network during business hours from managed devices."',
              '    Most flexible but most complex to implement.',
              '',
              'The principle underlying all of them:',
              '  LEAST PRIVILEGE — grant the minimum access needed to',
              '  perform the job. Nothing more. Review regularly.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Privilege escalation — what happens when access control fails.',
              '',
              '  VERTICAL ESCALATION',
              '    Low-privilege user gains high-privilege access.',
              '    Example: regular user becomes domain admin.',
              '    This is the attacker\'s primary goal after initial access.',
              '',
              '  HORIZONTAL ESCALATION',
              '    User accesses another user\'s data at the same privilege',
              '    level. Example: User A reads User B\'s email.',
              '    Often harder to detect because the access patterns',
              '    look "normal" in terms of privilege level.',
              '',
              'In investigations, you\'ll see both. The attacker phishes',
              'a regular user (horizontal — they now have that user\'s',
              'access). Then they escalate to admin (vertical — they now',
              'own the domain). The combination is a full compromise.',
            ],
          },
          {
            type: 'quiz',
            speaker: 'HANDLER',
            lines: [
              'A DI7 investigation reveals the following:',
              '  - A junior developer\'s account accessed the production',
              '    database containing customer financial records',
              '  - The developer\'s role should only grant access to the',
              '    staging environment',
              '  - No evidence of credential theft or malware',
              '  - The developer\'s access permissions were last reviewed 18 months ago',
            ],
            question: 'What is the most likely root cause?',
            options: [
              { id: 'creep', text: 'Privilege creep — permissions accumulated over role changes and were never revoked', correct: true },
              { id: 'insider', text: 'Insider threat — the developer intentionally accessed the data', correct: false },
              { id: 'exploit', text: 'Zero-day exploit in the RBAC system', correct: false },
            ],
          },
        ],
      },
      {
        id: 'protocol-security',
        title: 'Protocol Security',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Protocols are the rules systems use to communicate.',
              'When protocols have flaws, every system using them inherits',
              'those flaws.',
              '',
              '  CHALLENGE-RESPONSE AUTHENTICATION',
              '    Instead of sending your password, the server sends a',
              '    random challenge. You prove you know the password by',
              '    computing a response using the challenge + your password.',
              '    The password never crosses the wire.',
              '',
              '  MAN-IN-THE-MIDDLE (MITM)',
              '    Attacker positions themselves between client and server,',
              '    intercepting and potentially modifying traffic.',
              '    If the protocol doesn\'t verify the server\'s identity',
              '    (via TLS certificates), MITM is trivial.',
              '',
              '  TLS (Transport Layer Security)',
              '    The foundation of secure communication on the internet.',
              '    Encrypts traffic between client and server. Verifies',
              '    server identity via certificates. TLS 1.3 is the current',
              '    standard — it reduced the handshake to one round-trip',
              '    and removed all legacy weak cipher suites.',
              '',
              'If you see TLS 1.0 or 1.1 in an investigation, that system',
              'is using deprecated protocols with known vulnerabilities.',
            ],
          },
        ],
      },
    ],
  };
}
