import type { OrientationChapter } from './index.js';

export function getChapter05(): OrientationChapter {
  return {
    id: 'ch05-reading-wire',
    number: 5,
    title: 'Reading the Wire',
    subtitle: 'Network Fundamentals for Security',
    clearanceLevel: 'LEVEL 1 — RESTRICTED',
    tier: 2,
    estimatedMinutes: 30,
    sections: [
      {
        id: 'network-architecture',
        title: 'Network Architecture',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Every attack traverses a network. Understanding how networks',
              'are structured — and where defenses sit — is fundamental',
              'to both detecting and responding to threats.',
              '',
              'The TCP/IP model, simplified for our purposes:',
              '',
              '  APPLICATION LAYER  — HTTP, DNS, SMTP, SSH',
              '    Where users and attackers interact with services.',
              '    Most web attacks (XSS, SQL injection) happen here.',
              '',
              '  TRANSPORT LAYER   — TCP, UDP',
              '    Reliable delivery (TCP) or fast delivery (UDP).',
              '    Port numbers identify services: 80=HTTP, 443=HTTPS,',
              '    22=SSH, 25=SMTP, 53=DNS, 3389=RDP.',
              '',
              '  NETWORK LAYER     — IP',
              '    Addressing and routing. Source/destination IP addresses.',
              '    Where firewalls make allow/deny decisions.',
              '',
              '  LINK LAYER        — Ethernet, WiFi, ARP',
              '    Physical/local network communication.',
              '    ARP spoofing attacks happen here.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Network security boundaries — the chokepoints where',
              'defenses are deployed:',
              '',
              '  FIREWALL',
              '    Filters traffic based on rules: source IP, destination',
              '    IP, port, protocol. The primary perimeter defense.',
              '    Stateful firewalls track connections — they know the',
              '    difference between a new request and a response to',
              '    an existing connection.',
              '',
              '  IDS/IPS (Intrusion Detection/Prevention System)',
              '    Analyzes traffic patterns for known attack signatures.',
              '    IDS alerts. IPS blocks. Both generate the logs you',
              '    analyze during investigations.',
              '',
              '  PROXY / WEB APPLICATION FIREWALL (WAF)',
              '    Sits between users and web servers. Inspects HTTP',
              '    traffic for malicious payloads (SQL injection, XSS).',
              '    Can log full request/response bodies.',
              '',
              '  DMZ (Demilitarized Zone)',
              '    Network segment between the internet and internal',
              '    network. Public-facing servers (web, email, DNS) sit',
              '    here. Compromising a DMZ server shouldn\'t give access',
              '    to the internal network — if segmentation is done right.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              '  NETWORK SEGMENTATION',
              '    Dividing the network into zones with different trust',
              '    levels. Each zone has its own firewall rules.',
              '',
              '    Corporate network → can\'t directly reach server network',
              '    Server network → can\'t directly reach database network',
              '    Database network → only reachable from specific app servers',
              '',
              '    When segmentation fails, an attacker who compromises',
              '    one host can reach everything. That\'s called a "flat',
              '    network" — and it\'s how ransomware spreads from one',
              '    infected laptop to every server in the organization.',
              '',
              '  VPN (Virtual Private Network)',
              '    Encrypted tunnel between a remote user and the corporate',
              '    network. In the context of investigation: VPN logs show',
              '    when remote users connected, from what IP, for how long.',
              '    Unusual VPN sessions (2 AM from a foreign country) are',
              '    a common indicator of compromise.',
            ],
          },
        ],
      },
      {
        id: 'network-recon',
        title: 'Network Reconnaissance',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Reconnaissance is the first phase of the kill chain.',
              'Understanding what attackers look for helps you understand',
              'what to defend — and what to look for in your logs when',
              'someone is probing your perimeter.',
              '',
              '  PORT SCANNING (Nmap)',
              '    Probing IP addresses to find open ports and running',
              '    services. A SYN scan sends TCP SYN packets and watches',
              '    for SYN/ACK responses — indicating an open port.',
              '    In your firewall logs: hundreds of connection attempts',
              '    from a single IP to sequential ports = port scan.',
              '',
              '  SERVICE DETECTION',
              '    After finding open ports, identifying what software is',
              '    running and its version. Version information reveals',
              '    known vulnerabilities (CVEs) the attacker can exploit.',
              '',
              '  DNS ENUMERATION',
              '    Discovering subdomains: mail.company.com, vpn.company.com,',
              '    dev.company.com, staging.company.com.',
              '    Each subdomain is a potential entry point.',
              '    Tools: DNS zone transfers, brute-force subdomain lists,',
              '    certificate transparency logs.',
            ],
          },
          {
            type: 'guided-command',
            speaker: 'HANDLER',
            expectedCommand: 'scan network --target=10.10.0.0/16',
            commandPatterns: ['scan network --target=10.10.0.0/16', 'scan network --target=10.10.0.0'],
            lines: [
              'Run a scan of the internal network. See what\'s exposed.',
            ],
            commandOutput: `═══ NETWORK SCAN: 10.10.0.0/16 (Internal) ══════════════

HOST           PORT    SERVICE              VERSION              NOTES
─────────────────────────────────────────────────────────────────────
10.10.1.5      22      SSH                  OpenSSH 8.9
10.10.1.5      80      HTTP                 nginx 1.18           Redirect → HTTPS
10.10.1.5      443     HTTPS                nginx 1.18           TLS 1.2+
10.10.2.10     22      SSH                  OpenSSH 7.4          !! OUTDATED !!
10.10.2.10     3306    MySQL                5.7.38               !! EXPOSED !!
10.10.2.10     8080    HTTP                 Apache Tomcat 9.0.30 !! EXPOSED ADMIN !!
10.10.3.1      53      DNS                  BIND 9.16
10.10.3.1      389     LDAP                 OpenLDAP 2.4
10.10.5.20     135     MSRPC                Windows Server 2019
10.10.5.20     445     SMB                  Windows Server 2019
10.10.5.20     3389    RDP                  Windows Server 2019  !! OPEN !!

Hosts discovered: 4 | Open ports: 11 | Critical findings: 3`,
            explanation: [
              'Three critical findings:',
              '',
              '10.10.2.10 — MySQL port 3306 exposed on the network.',
              'Database ports should NEVER be directly accessible from',
              'the general network. This should be firewalled to only',
              'the application servers that need it.',
              '',
              '10.10.2.10 — Tomcat admin on 8080, exposed. An attacker',
              'on the network could deploy a malicious web application',
              'directly to this server.',
              '',
              '10.10.5.20 — RDP open. Remote Desktop Protocol is one of',
              'the most targeted services. If credentials are weak or',
              'stolen, the attacker gets a full desktop session.',
              '',
              'Also note: OpenSSH 7.4 on 10.10.2.10 is years out of date.',
              'Likely has known CVEs.',
            ],
            hintOnWrong: 'Type: scan network --target=10.10.0.0/16',
          },
        ],
      },
      {
        id: 'traffic-analysis',
        title: 'Traffic Analysis',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Firewall and proxy logs tell you what happened on the',
              'network. Packet captures tell you exactly what was said.',
              '',
              'Key traffic patterns to recognize:',
              '',
              '  BEACONING',
              '    Malware regularly "phones home" to its C2 server at',
              '    fixed intervals: every 60 seconds, every 5 minutes.',
              '    In firewall logs: same source IP, same destination IP,',
              '    regular intervals, small data packets. This regularity',
              '    is the telltale — legitimate traffic is irregular.',
              '',
              '  DATA EXFILTRATION',
              '    Large outbound data transfers to unusual destinations.',
              '    In firewall logs: high byte counts to external IPs,',
              '    especially to IP addresses with no legitimate business',
              '    relationship. Often happens after hours.',
              '',
              '  DNS TUNNELING',
              '    Encoding data inside DNS queries to bypass firewalls.',
              '    In DNS logs: extremely long subdomain names, high query',
              '    volume to a single domain, encoded-looking strings.',
              '    Example: aGVsbG8gd29ybGQ.evil-tunnel.com',
              '    That subdomain is Base64-encoded data.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              '  LATERAL MOVEMENT',
              '    After compromising one host, attackers move to others.',
              '    In network logs: SMB connections between workstations',
              '    (workstations rarely talk to each other directly),',
              '    RDP sessions from server to server, WMI remote execution.',
              '',
              '  PORT HOPPING / PROTOCOL ABUSE',
              '    Attackers use allowed ports for unauthorized purposes.',
              '    Example: tunneling SSH over port 443 (HTTPS) to bypass',
              '    firewalls that only allow web traffic.',
              '    In logs: port 443 traffic that isn\'t actually TLS.',
              '',
              '  ANOMALOUS VOLUME',
              '    Sudden spikes in traffic volume. Could be DDoS,',
              '    could be data exfiltration, could be cryptomining.',
              '    Baselining normal traffic helps identify anomalies.',
            ],
          },
          {
            type: 'guided-command',
            speaker: 'HANDLER',
            expectedCommand: 'logs show --source=firewall --search=198.51.100',
            commandPatterns: ['logs show --source=firewall --search=198.51.100', 'logs show --source=firewall'],
            lines: [
              'Examine the firewall logs. Look for the attacker IP range',
              'from Chapter 3.',
            ],
            commandOutput: `═══ FIREWALL LOGS (filtered: 198.51.100.*) ══════════════

[06:34:18] ALLOW  198.51.100.88:443 → 172.16.0.5:993  IMAP/TLS    847KB outbound
[06:34:19] ALLOW  198.51.100.88:443 → 172.16.0.20:443 Drive API   2.1MB outbound
[07:00:00] ALLOW  198.51.100.88:443 → 172.16.0.5:993  IMAP/TLS    12KB outbound
[07:05:00] ALLOW  198.51.100.88:443 → 172.16.0.5:993  IMAP/TLS    12KB outbound
[07:10:00] ALLOW  198.51.100.88:443 → 172.16.0.5:993  IMAP/TLS    12KB outbound
[07:15:00] ALLOW  198.51.100.88:443 → 172.16.0.5:993  IMAP/TLS    12KB outbound
[07:20:00] ALLOW  198.51.100.88:443 → 172.16.0.5:993  IMAP/TLS    12KB outbound

Pattern detected: BEACONING — 5-minute intervals, consistent packet size
Total egress to 198.51.100.0/24: 3.1MB`,
            explanation: [
              'Classic beaconing pattern. After the initial data theft',
              '(847KB + 2.1MB), the attacker\'s access settles into a',
              'regular 5-minute check-in: same destination, same port,',
              'same 12KB packet size, exactly 5 minutes apart.',
              '',
              'This regularity is what makes C2 traffic detectable.',
              'Legitimate users don\'t make requests at perfectly regular',
              'intervals with identical data sizes. Humans are messy.',
              'Malware is precise.',
              '',
              'Sophisticated adversaries add jitter — random ±30 second',
              'offsets to their beacon interval — to look more human.',
              'But the pattern is still there if you look closely.',
            ],
            hintOnWrong: 'Type: logs show --source=firewall --search=198.51.100',
          },
        ],
      },
      {
        id: 'lateral-movement',
        title: 'Lateral Movement — How Attackers Spread',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Initial access gets the attacker a foothold. Lateral',
              'movement is how they expand that foothold into full',
              'network control. This is where most damage happens.',
              '',
              '  PASS-THE-HASH (PtH)',
              '    Windows stores password hashes in memory (LSASS process).',
              '    An attacker with admin access on one machine can extract',
              '    these hashes and use them to authenticate to other',
              '    machines — without knowing the actual passwords.',
              '    Tool: Mimikatz, the single most important tool in red',
              '    team operations.',
              '',
              '  KERBEROASTING',
              '    Active Directory uses Kerberos for authentication.',
              '    Service accounts have "Service Principal Names" (SPNs).',
              '    Any domain user can request a Kerberos ticket for any SPN.',
              '    That ticket is encrypted with the service account\'s password',
              '    hash — which can be cracked offline. If the service account',
              '    password is weak, the attacker gets those credentials.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'REN',
            lines: [
              'Let me add the red team perspective here.',
              '',
              'When I\'m running an operation against a target, my path',
              'from initial access to domain admin typically goes:',
              '',
              '  1. Phish a user → get their workstation',
              '  2. Dump LSASS on their workstation → get cached creds',
              '  3. Use those creds to move to a server (PtH or RDP)',
              '  4. On the server, find service account creds or run',
              '     Kerberoasting to get more powerful accounts',
              '  5. Find a path to Domain Admin via BloodHound',
              '  6. DCSync — replicate the domain controller\'s password',
              '     database. Game over. I have every password hash.',
              '',
              'Total time from phishing email to domain admin:',
              'in a poorly segmented network? Under 4 hours.',
              '',
              'Your job as an Observer is to detect this chain BEFORE',
              'step 6. Ideally at step 2 or 3.',
            ],
          },
          {
            type: 'quiz',
            speaker: 'HANDLER',
            lines: [
              'You observe the following in authentication logs:',
              '  - 10:14 — User "jsmith" logs into WORKSTATION-42 (normal)',
              '  - 10:22 — WORKSTATION-42 makes NTLM auth to SERVER-DB',
              '    using account "svc_backup" (service account)',
              '  - 10:23 — svc_backup account accesses Active Directory',
              '    and requests replication data from the domain controller',
            ],
            question: 'What attack sequence is this?',
            options: [
              { id: 'correct', text: 'Credential theft → lateral movement → DCSync attack targeting domain controller', correct: true },
              { id: 'recon', text: 'Reconnaissance — the user is scanning the network', correct: false },
              { id: 'normal', text: 'Normal backup operations using the service account', correct: false },
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'That sequence — credential theft, lateral movement via',
              'service account, DCSync — is the most common path to total',
              'domain compromise. It happened in 8 minutes.',
              '',
              'Detection points:',
              '  • LSASS access from non-security tools (step 2)',
              '  • Service account used from a workstation, not a server (step 2-3)',
              '  • Replication requests from a non-DC machine (step 3)',
              '',
              'Each of these generates detectable log events. The question',
              'is whether anyone is looking for them.',
              '',
              'This chapter covered network architecture, reconnaissance,',
              'traffic analysis, and lateral movement. In the next chapter,',
              'we shift to the human side — social engineering.',
            ],
          },
        ],
      },
    ],
  };
}
