import type { OrientationChapter } from './index.js';

export function getChapter06(): OrientationChapter {
  return {
    id: 'ch06-human-factor',
    number: 6,
    title: 'The Human Factor',
    subtitle: 'Social Engineering & Deception',
    clearanceLevel: 'LEVEL 1 — RESTRICTED',
    tier: 2,
    estimatedMinutes: 25,
    sections: [
      // ═══════════════════════════════════════════
      // SECTION 1: PSYCHOLOGY OF DECEPTION
      // ═══════════════════════════════════════════
      {
        id: 'psychology-of-deception',
        title: 'Psychology of Deception',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Every system we\'ve examined so far has one thing in common:',
              'a human being sits between the attacker and the asset.',
              'Firewalls, encryption, access controls — all of it is',
              'irrelevant if you can convince a person to open the door.',
              '',
              'Social engineering is the exploitation of human psychology.',
              'It\'s the oldest attack vector and still the most effective.',
              'Over 80% of breaches involve a human element. Not because',
              'people are stupid — because the brain has predictable',
              'shortcuts that attackers know how to trigger.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Five cognitive biases that attackers weaponize:',
              '',
              '  AUTHORITY',
              '    Humans defer to perceived authority figures. An email',
              '    "from the CEO" demanding an urgent wire transfer bypasses',
              '    normal caution. The attacker doesn\'t need to be the CEO.',
              '    They need to appear to be the CEO for 30 seconds.',
              '',
              '  URGENCY',
              '    Time pressure disables critical thinking. "Your account',
              '    will be suspended in 15 minutes." "This wire must clear',
              '    before end of business." Urgency forces action before',
              '    verification.',
              '',
              '  RECIPROCITY',
              '    If someone does you a favor, you feel obligated to return',
              '    it. An attacker calls IT support, is friendly, empathizes',
              '    with the tech\'s workload — then asks for "a small favor"',
              '    like resetting a password. The tech complies because the',
              '    social contract demands it.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              '  SOCIAL PROOF',
              '    "Everyone else has already completed this compliance',
              '    form." "Your colleagues all updated their credentials',
              '    this morning." If the herd is doing it, it must be safe.',
              '    Attackers fabricate consensus to reduce suspicion.',
              '',
              '  SCARCITY',
              '    Limited-time offers, exclusive access, "only 3 seats',
              '    remaining." Scarcity triggers fear of missing out,',
              '    which overrides analysis. Phishing campaigns that',
              '    mimic exclusive invitations exploit this instinct.',
              '',
              'These aren\'t theoretical. They\'re the building blocks of',
              'every phishing email, every vishing call, every pretexting',
              'operation you\'ll encounter in the field.',
              '',
              'The social-brain theory explains why: human cognition',
              'evolved for cooperation in small groups, not adversarial',
              'digital communication. Our trust calibration assumes',
              'good faith by default. Attackers exploit that default.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Why smart people fall for phishing.',
              '',
              'Intelligence doesn\'t protect against social engineering.',
              'In many cases, it makes the target more vulnerable —',
              'intelligent people are more confident in their ability to',
              'detect deception, which lowers their guard.',
              '',
              'Factors that increase susceptibility:',
              '',
              '  - High cognitive load (busy, stressed, multitasking)',
              '  - Context that matches expectations (you were expecting',
              '    a DocuSign — so you click the DocuSign email)',
              '  - Mobile devices (smaller screens hide URL details)',
              '  - Emotional state (anger, excitement, fear)',
              '  - Time of day (early morning, late evening — fatigue)',
              '',
              'The Hargrove breach in Chapter 3 — a managing partner',
              'at a law firm. Highly intelligent. Highly educated.',
              'Clicked the phishing link because the lure matched',
              'a merger he was actually working on. Context was the weapon.',
            ],
          },
        ],
      },

      // ═══════════════════════════════════════════
      // SECTION 2: PHISHING ANATOMY
      // ═══════════════════════════════════════════
      {
        id: 'phishing-anatomy',
        title: 'Phishing Anatomy',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Phishing analysis is a core skill. You need to read',
              'email headers the way a medic reads vitals — quickly,',
              'accurately, and with a clear diagnosis.',
              '',
              'Key headers and what they reveal:',
              '',
              '  Return-Path',
              '    The actual envelope sender. If this doesn\'t match the',
              '    From header, the sender is spoofing. Legitimate email:',
              '    Return-Path matches From domain. Phishing: they diverge.',
              '',
              '  Received (chain)',
              '    Each mail server that handled the message adds a Received',
              '    header. Read bottom-to-top to trace the email\'s path.',
              '    Legitimate mail: consistent corporate servers.',
              '    Phishing: random VPS IPs, foreign hosting, mismatched hops.',
              '',
              '  SPF (Sender Policy Framework)',
              '    DNS record listing which IPs are authorized to send email',
              '    for a domain. SPF PASS = sent from an authorized server.',
              '    SPF FAIL = sent from an unauthorized server. Hard fail.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              '  DKIM (DomainKeys Identified Mail)',
              '    Cryptographic signature proving the email wasn\'t altered',
              '    in transit and was sent by the claimed domain. DKIM PASS',
              '    means the sending server held the domain\'s private key.',
              '    DKIM FAIL or NONE = the domain did not sign this message.',
              '',
              '  DMARC (Domain-based Message Authentication)',
              '    Policy that combines SPF + DKIM results and tells the',
              '    receiving server what to do on failure: none (do nothing),',
              '    quarantine (send to spam), reject (block delivery).',
              '    DMARC PASS requires either SPF or DKIM to pass AND align',
              '    with the From domain.',
              '',
              'When all three fail — SPF FAIL, DKIM NONE, DMARC FAIL —',
              'the email is almost certainly not from who it claims to be.',
              'That was the signature on every email in the Hargrove case.',
              '',
              'Beyond headers — domain deception techniques:',
              '',
              '  TYPOSQUATTING      — g00gle.com, microsft.com, arnazon.com',
              '  HOMOGLYPH ATTACKS  — Using Unicode characters that look',
              '                       identical: "а" (Cyrillic) vs "a" (Latin)',
              '  DISPLAY NAME SPOOF — "IT Security <phish@evil.com>"',
              '  DOPPELGANGER       — company-support.com vs company.com',
            ],
          },
          {
            type: 'quiz',
            speaker: 'HANDLER',
            lines: [
              'Classify each email. I\'ll present four — tell me which',
              'is the phishing attempt.',
              '',
              '  EMAIL A:',
              '    From: payroll@company.com',
              '    Return-Path: payroll@company.com',
              '    SPF: PASS  DKIM: PASS  DMARC: PASS',
              '    Subject: "Updated W-2 forms available in HR portal"',
              '    Link: https://hr.company.com/documents',
              '',
              '  EMAIL B:',
              '    From: security@microsoft.com',
              '    Return-Path: noreply@msft-security-alert.net',
              '    SPF: FAIL  DKIM: NONE  DMARC: FAIL',
              '    Subject: "Unusual sign-in activity on your account"',
              '    Link: https://login.microsoftonIine.com/verify',
              '',
              '  EMAIL C:',
              '    From: jira@atlassian.net',
              '    Return-Path: jira@atlassian.net',
              '    SPF: PASS  DKIM: PASS  DMARC: PASS',
              '    Subject: "JIRA-4521 assigned to you"',
              '    Link: https://yourteam.atlassian.net/browse/JIRA-4521',
              '',
              '  EMAIL D:',
              '    From: noreply@github.com',
              '    Return-Path: noreply@github.com',
              '    SPF: PASS  DKIM: PASS  DMARC: PASS',
              '    Subject: "You have a new pull request review"',
              '    Link: https://github.com/org/repo/pull/847',
            ],
            question: 'Which email is the phishing attempt?',
            options: [
              { id: 'a', text: 'Email A — the payroll email', correct: false },
              { id: 'b', text: 'Email B — the Microsoft security alert', correct: true },
              { id: 'c', text: 'Email C — the Jira notification', correct: false },
              { id: 'd', text: 'Email D — the GitHub notification', correct: false },
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Email B. Every indicator is red.',
              '',
              'Return-Path (msft-security-alert.net) doesn\'t match From',
              '(microsoft.com). SPF FAIL, DKIM NONE, DMARC FAIL. The link',
              'domain uses "microsoftonIine" — that\'s a capital I replacing',
              'the lowercase L in "online." A homoglyph attack.',
              '',
              'The others all have consistent headers, passing authentication,',
              'and legitimate domains. Email A\'s link goes to the actual',
              'company HR portal. C and D point to real Atlassian and GitHub',
              'domains.',
              '',
              'In practice, you won\'t always have four emails side by side.',
              'You\'ll have one, and you\'ll need to make the call in seconds.',
              'Train the pattern recognition. Headers first. Domain second.',
              'Content third.',
            ],
          },
        ],
      },

      // ═══════════════════════════════════════════
      // SECTION 3: ADVANCED SOCIAL ENGINEERING
      // ═══════════════════════════════════════════
      {
        id: 'advanced-social-engineering',
        title: 'Advanced Social Engineering',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Email phishing is entry-level. Sophisticated adversaries',
              'use multi-channel, multi-stage social engineering campaigns.',
              '',
              '  PRETEXTING',
              '    Building a fabricated scenario to extract information.',
              '    The attacker becomes a character: IT auditor, vendor',
              '    rep, new hire, building inspector. They research the',
              '    target organization — names, org charts, projects —',
              '    to make the pretext convincing.',
              '    "Hi, this is Mike from the Dallas office. Sarah in',
              '    accounting told me to call you about the Q4 audit."',
              '    If Mike, Sarah, and the audit are all real, the target',
              '    has no reason to suspect the caller isn\'t legitimate.',
              '',
              '  VISHING (Voice Phishing)',
              '    Phone-based social engineering. Caller ID can be spoofed.',
              '    The attacker calls the help desk, impersonates an',
              '    executive, claims they\'re locked out and need a password',
              '    reset. Urgency + authority. The help desk complies.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              '  SMISHING (SMS Phishing)',
              '    Text message attacks. Shorter URLs are harder to inspect.',
              '    "Your package delivery failed. Confirm address:"',
              '    followed by a shortened link. Mobile users are',
              '    especially vulnerable — no hover-to-preview, smaller',
              '    screens, faster decision-making.',
              '',
              '  WATERING HOLE ATTACKS',
              '    Compromise a website your target already visits.',
              '    Instead of phishing the target directly, you infect',
              '    the industry news site, the professional association',
              '    forum, or the vendor portal they log into daily.',
              '    The target comes to you. No suspicious email required.',
              '',
              '  BUSINESS EMAIL COMPROMISE (BEC)',
              '    The apex predator of social engineering. The attacker',
              '    gains access to a real executive\'s email (often via',
              '    phishing), then uses that legitimate account to request',
              '    wire transfers, data exports, or credential changes.',
              '    No spoofed domains. No failed SPF checks. The email',
              '    IS from the CEO — the CEO\'s account is compromised.',
              '    BEC caused $2.9 billion in reported losses in a single year.',
            ],
          },
          {
            type: 'scenario',
            speaker: 'HANDLER',
            scenarioContext: 'A CFO receives a call from someone claiming to be the company\'s external auditor. The caller references the correct audit firm name, the CFO\'s assistant by name, and a real upcoming board meeting. They request the CFO email a preliminary financial summary to a "new secure portal" for pre-review. The email address provided is at the auditor\'s domain, but with a subtle typosquat.',
            lines: [
              'Scenario. Assess this situation.',
              '',
              'Your SIEM flags an anomaly: the CFO of a DI7 client just',
              'sent a 4MB file to an external address. The address appears',
              'to belong to their audit firm — but you notice the domain',
              'is one character off.',
              '',
              'You pull the phone logs. The CFO received a 12-minute call',
              'from a spoofed number matching the audit firm\'s main line.',
              'During the call, the CFO was addressed by name, the caller',
              'referenced the correct audit partner, the correct assistant,',
              'and a real board meeting scheduled for next week.',
              '',
              'This is a multi-channel pretexting attack: vishing to build',
              'trust, followed by a targeted data exfiltration request.',
              'The attacker did extensive reconnaissance — org charts,',
              'LinkedIn profiles, SEC filings for board meeting dates.',
              '',
              'The pretext was nearly flawless. The single point of',
              'failure: the typosquatted email domain. That\'s what your',
              'systems caught. Without that detection, the financial',
              'summary would have been exfiltrated cleanly.',
            ],
          },
          {
            type: 'quiz',
            speaker: 'HANDLER',
            lines: [
              'Based on the scenario above — the vishing call to the CFO',
              'followed by the exfiltration request — which social',
              'engineering principles were weaponized?',
            ],
            question: 'Which combination of principles did the attacker use?',
            options: [
              { id: 'correct', text: 'Authority (audit firm), social proof (naming colleagues), urgency (upcoming board meeting)', correct: true },
              { id: 'partial', text: 'Only authority — the attacker impersonated the auditor', correct: false },
              { id: 'wrong', text: 'Scarcity and reciprocity — the attacker offered something first', correct: false },
            ],
          },
        ],
      },

      // ═══════════════════════════════════════════
      // SECTION 4: BUILDING RESILIENCE
      // ═══════════════════════════════════════════
      {
        id: 'building-resilience',
        title: 'Building Resilience',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Defense against social engineering is layered — technical',
              'controls, process controls, and human awareness working',
              'together. No single layer is sufficient.',
              '',
              '  TECHNICAL',
              '    Email authentication (SPF/DKIM/DMARC with reject policy)',
              '    URL rewriting and sandboxing (detonate links in isolation)',
              '    Attachment sandboxing (execute files in a controlled env)',
              '    Domain monitoring (detect typosquats of your brand)',
              '',
              '  PROCESS',
              '    Out-of-band verification for financial transactions',
              '    ("Call them back on a known number, not the one they gave you")',
              '    Dual authorization for wire transfers over thresholds',
              '    Escalation procedures for unusual requests',
              '',
              '  HUMAN',
              '    Realistic phishing simulations — not gotcha exercises,',
              '    but genuine training that builds pattern recognition.',
              '    Blameless reporting culture — if people fear punishment',
              '    for clicking, they won\'t report. And unreported phishing',
              '    is undetected phishing.',
            ],
          },
          {
            type: 'decision',
            speaker: 'HANDLER',
            lines: [
              'A mid-size financial firm has been hit by three BEC',
              'attacks in six months. Each time, an executive\'s email',
              'was compromised via phishing and used to request wire',
              'transfers. Total losses: $1.2 million.',
              '',
              'The firm\'s current defenses: basic spam filtering, annual',
              'security awareness training (slide deck, 45 minutes),',
              'and single-factor email authentication.',
              '',
              'You\'re advising on the response. What\'s your priority?',
            ],
            question: 'What is your recommended first action?',
            options: [
              {
                id: 'mfa-plus-process',
                text: 'Deploy hardware MFA for all executives and implement out-of-band verification for wire transfers',
                correct: true,
              },
              {
                id: 'training-only',
                text: 'Increase phishing awareness training frequency to monthly',
                correct: false,
              },
              {
                id: 'tech-only',
                text: 'Deploy an advanced email security gateway with AI-based threat detection',
                correct: false,
              },
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Hardware MFA plus process controls. Here\'s the logic.',
              '',
              'The root cause is twofold: executive accounts are being',
              'compromised (authentication failure), and fraudulent wire',
              'requests are being fulfilled without verification (process',
              'failure). You need to address both.',
              '',
              'Hardware MFA (FIDO2 keys) makes the phishing attacks that',
              'lead to account compromise dramatically harder — the key',
              'verifies the domain, so credential-harvesting pages fail.',
              'Out-of-band verification means even if an account IS',
              'compromised, the wire transfer requires a phone call to',
              'a known number. Two independent failures must occur.',
              '',
              'Training alone won\'t stop determined attackers. Technology',
              'alone won\'t catch sophisticated pretexting. The combination',
              'of technical and process controls provides defense in depth.',
              '',
              'This chapter covered the human element — the cognitive',
              'biases, the attack techniques, and the countermeasures.',
              'Next: we shift to application-layer attacks. The web has',
              'its own vulnerabilities, and they\'re everywhere.',
            ],
          },
        ],
      },
    ],
  };
}
