import type { OrientationChapter } from './index.js';

export function getChapter08(): OrientationChapter {
  return {
    id: 'ch08-breaching',
    number: 8,
    title: 'Breaching the Perimeter',
    subtitle: 'How Attackers Get In',
    clearanceLevel: 'LEVEL 2 — CLASSIFIED',
    tier: 3,
    estimatedMinutes: 35,
    sections: [
      // ═══════════════════════════════════════════
      // SECTION 1: RED VS BLUE
      // ═══════════════════════════════════════════
      {
        id: 'red-vs-blue',
        title: 'Red vs Blue',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'This chapter covers offensive operations. Red team',
              'tradecraft — the techniques attackers use to breach',
              'organizations from the outside in.',
              '',
              'Why study offense? Because you cannot defend against',
              'what you don\'t understand. The best blue team operators',
              'have red team knowledge. They think like the adversary.',
              'They anticipate the next move instead of reacting to it.',
              '',
              '  RED TEAM — simulates real-world adversaries. Their job',
              '    is to find a way in, escalate access, and prove impact.',
              '    No vulnerabilities off limits. Social engineering,',
              '    physical access, technical exploitation — all in scope.',
              '',
              '  BLUE TEAM — defends. Detects, responds, contains.',
              '    Your role as an Observer is blue team, but with red',
              '    team awareness.',
              '',
              '  ASSUMED BREACH — a methodology that skips the question',
              '    "can they get in?" and starts with "they\'re already in.',
              '    Now what?" Increasingly the standard for mature',
              '    security programs.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'REN',
            lines: [
              'Handler asked me to give you the view from the other side.',
              '',
              'I run red team operations for DI7. My job is to break into',
              'organizations that hired us to test their defenses. Legal,',
              'sanctioned, documented — but the techniques are real.',
              '',
              'Here\'s what most people don\'t understand about red teaming:',
              'the goal isn\'t to find vulnerabilities. Scanners find',
              'vulnerabilities. The goal is to demonstrate impact.',
              '',
              '"We found an unpatched server" doesn\'t move budgets.',
              '"We used that server to access your CEO\'s email and',
              'exfiltrate next quarter\'s earnings before they were public"',
              '— that moves budgets.',
              '',
              'Every red team operation tells a story. Initial access,',
              'lateral movement, objective completion. The story is what',
              'convinces leadership to invest in security. Technical',
              'findings alone rarely do.',
              '',
              'I\'ll walk you through the playbook.',
            ],
          },
        ],
      },

      // ═══════════════════════════════════════════
      // SECTION 2: INITIAL ACCESS VECTORS
      // ═══════════════════════════════════════════
      {
        id: 'initial-access-vectors',
        title: 'Initial Access Vectors',
        steps: [
          {
            type: 'narrative',
            speaker: 'REN',
            lines: [
              'Initial access — getting the first foothold. The hardest',
              'part of an operation. Once you\'re in, everything gets easier.',
              '',
              '  PHISHING WITH WEAPONIZED DOCUMENTS',
              '    The classic. Send a document that executes code when opened.',
              '',
              '    MACRO-ENABLED OFFICE DOCS (.docm, .xlsm)',
              '      VBA macros execute when the user clicks "Enable Content."',
              '      The macro downloads and executes a payload. Microsoft has',
              '      tightened defaults — macros from the internet are now',
              '      blocked by default in newer Office versions. But legacy',
              '      environments and workarounds persist.',
              '',
              '    DDE (Dynamic Data Exchange)',
              '      Embeds commands in document fields. No macros required.',
              '      The user sees a prompt: "This document contains links',
              '      to other files. Update?" If they click yes, the command',
              '      executes. Quieter than macros — no "Enable Content" banner.',
              '',
              '    HTA (HTML Application)',
              '      .hta files run as fully trusted applications in Windows.',
              '      Combine HTML with VBScript or JScript. Full access to',
              '      the file system and registry. Often delivered via phishing',
              '      as "invoice.hta" or embedded in email links.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'REN',
            lines: [
              '  EXPLOITING PUBLIC-FACING APPLICATIONS',
              '    Any service exposed to the internet is a target.',
              '    VPN appliances (Fortinet, Pulse Secure, Citrix) have had',
              '    critical RCE vulnerabilities. Exchange servers (ProxyLogon,',
              '    ProxyShell) gave attackers remote code execution with no',
              '    credentials. Web applications with SQL injection, file',
              '    upload, or deserialization flaws.',
              '    Patch latency is the enemy — the exploit is public days',
              '    after the CVE. Organizations that take weeks to patch',
              '    are compromised in that window.',
              '',
              '  VALID ACCOUNT COMPROMISE',
              '    Why exploit a vulnerability when you can just log in?',
              '    Credential stuffing from data breaches. Brute-forcing',
              '    weak passwords. Purchasing credentials from initial',
              '    access brokers on underground markets. VPN credentials',
              '    are particularly valuable — they bypass the perimeter entirely.',
              '',
              '  SUPPLY CHAIN ATTACKS',
              '    Compromise a vendor, MSP, or software supplier that has',
              '    trusted access to the target. SolarWinds: attackers',
              '    injected a backdoor into a software update. 18,000',
              '    organizations installed it voluntarily. Kaseya: a',
              '    vulnerability in IT management software was used to',
              '    deploy ransomware to managed service providers and',
              '    their downstream clients simultaneously.',
            ],
          },
          {
            type: 'quiz',
            speaker: 'HANDLER',
            lines: [
              'An organization discovers that their VPN appliance has been',
              'compromised. Investigation reveals:',
              '  - CVE-2023-27997 (Fortinet SSL-VPN RCE) was exploited',
              '  - The patch was available for 47 days before exploitation',
              '  - The attacker created a local admin account on the appliance',
              '  - VPN logs show connections from the attacker\'s account to',
              '    internal servers for the past 3 weeks',
            ],
            question: 'What initial access vector was used, and what enabled it?',
            options: [
              { id: 'correct', text: 'Exploiting a public-facing application — enabled by a 47-day patch gap on a critical internet-facing device', correct: true },
              { id: 'supply', text: 'Supply chain attack — the VPN vendor was compromised', correct: false },
              { id: 'creds', text: 'Valid account compromise — the attacker had stolen VPN credentials', correct: false },
              { id: 'phish', text: 'Phishing — an employee was tricked into installing the backdoor', correct: false },
            ],
          },
          {
            type: 'narrative',
            speaker: 'REN',
            lines: [
              'One thing I\'ll add on initial access — the economics.',
              '',
              'Initial access brokers are a real market. A group compromises',
              'VPN credentials or installs a web shell, then sells that',
              'access to the highest bidder. Ransomware operators buy access',
              'rather than doing the work themselves.',
              '',
              'Price list from underground markets (as of our latest intel):',
              '',
              '  VPN credentials (Fortune 500)     — $5,000-$25,000',
              '  Domain Admin access (mid-size org) — $10,000-$50,000',
              '  Web shell on e-commerce site       — $500-$2,000',
              '  RDP access (single server)         — $10-$100',
              '',
              'The specialization is key. The group that finds the initial',
              'vulnerability is not the same group that deploys ransomware.',
              'The supply chain of cybercrime mirrors legitimate business.',
            ],
          },
        ],
      },

      // ═══════════════════════════════════════════
      // SECTION 3: POST-EXPLOITATION
      // ═══════════════════════════════════════════
      {
        id: 'post-exploitation',
        title: 'Post-Exploitation',
        steps: [
          {
            type: 'narrative',
            speaker: 'REN',
            lines: [
              'You\'re in. One machine. Low-privilege user account.',
              'Now what?',
              '',
              '  CREDENTIAL HARVESTING',
              '    First priority: get more credentials. Credentials unlock',
              '    lateral movement.',
              '',
              '    LSASS MEMORY DUMP',
              '      The LSASS process (Local Security Authority Subsystem)',
              '      on Windows holds cached credentials in memory. Tools',
              '      like Mimikatz read LSASS memory and extract:',
              '        - NTLM password hashes',
              '        - Kerberos tickets',
              '        - Cleartext passwords (in some configurations)',
              '      Requires local admin on the compromised host.',
              '      Defense: Credential Guard, Protected Process Light (PPL),',
              '      and monitoring for LSASS access events.',
              '',
              '    SAM DATABASE',
              '      Local account hashes stored in the Security Account',
              '      Manager. Extractable with local admin privileges.',
              '      Useful for local admin password reuse across hosts.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'REN',
            lines: [
              '  PRIVILEGE ESCALATION',
              '',
              '    LOCAL ESCALATION',
              '      From standard user to local admin. Techniques:',
              '        - Unquoted service paths (Windows)',
              '        - DLL hijacking (missing DLL in a writable path)',
              '        - Misconfigured services (running as SYSTEM with',
              '          writable binaries)',
              '        - Kernel exploits (local privilege escalation CVEs)',
              '        - Sudo misconfigurations (Linux)',
              '',
              '    DOMAIN ESCALATION',
              '      From domain user to domain admin. This is the prize.',
              '      We\'ll cover specific AD attacks in the next section.',
              '',
              '  PERSISTENCE',
              '    Once you have access, you need to keep it. Red teams',
              '    (and real attackers) install persistence mechanisms:',
              '      - Scheduled tasks / cron jobs',
              '      - Registry Run keys (Windows startup)',
              '      - WMI event subscriptions',
              '      - DLL side-loading',
              '      - Web shells (for web server access)',
              '      - Backdoor user accounts',
              '    Good persistence survives reboots, password changes,',
              '    and basic incident response.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'REN',
            lines: [
              '  LIVING OFF THE LAND (LOL)',
              '    Using built-in operating system tools instead of',
              '    custom malware. If your tools are already on the system,',
              '    there\'s nothing to detect as "malicious software."',
              '',
              '    POWERSHELL',
              '      The Swiss army knife of Windows post-exploitation.',
              '      Download files: Invoke-WebRequest',
              '      Execute in memory: IEX(New-Object Net.WebClient).DownloadString()',
              '      Credential access: Get-Credential, Invoke-Mimikatz',
              '      Remote execution: Invoke-Command -ComputerName',
              '      All of this is "legitimate" PowerShell usage from the',
              '      OS perspective.',
              '',
              '    WMI (Windows Management Instrumentation)',
              '      Remote command execution, event subscriptions, system',
              '      enumeration — all built into Windows. WMI lateral',
              '      movement leaves minimal forensic artifacts compared',
              '      to PsExec or RDP.',
              '',
              '    CERTUTIL, BITSADMIN, MSHTA',
              '      Legitimate Windows utilities that can download and',
              '      execute files. Often allowed through application',
              '      whitelists because they\'re "system tools."',
            ],
          },
          {
            type: 'scenario',
            speaker: 'HANDLER',
            scenarioContext: 'Complete kill chain from phishing to domain compromise. The Observer traces every step of the attack timeline using logs.',
            lines: [
              'Scenario. Trace the full kill chain.',
              '',
              'OMNIUS has flagged an incident at a DI7 client. Here\'s the',
              'timeline reconstructed from multiple log sources:',
              '',
              '  09:14  EMAIL — User j.santos receives Word doc "Q4_Report.docm"',
              '         from a spoofed partner email address.',
              '  09:17  ENDPOINT — j.santos opens the document. Macro executes.',
              '         PowerShell spawns from winword.exe.',
              '  09:17  NETWORK — PowerShell downloads payload from 185.220.101.44',
              '         using Invoke-WebRequest. No executable written to disk.',
              '  09:18  ENDPOINT — Payload runs in memory. Establishes C2 beacon',
              '         to 185.220.101.44:443 (HTTPS, blends with normal traffic).',
              '  09:24  ENDPOINT — Attacker dumps LSASS. Extracts NTLM hash for',
              '         j.santos and cached domain admin hash (svc_deploy).',
              '  09:31  NETWORK — Pass-the-hash lateral movement to file server',
              '         FS01 using svc_deploy hash.',
              '  09:33  ENDPOINT — Scheduled task created on FS01 for persistence.',
              '  09:41  NETWORK — DCSync replication request from FS01 to domain',
              '         controller. All domain password hashes exfiltrated.',
              '',
              'Total time from phishing email to domain compromise: 27 minutes.',
              'Every step used legitimate Windows tools. No malware on disk.',
            ],
          },
        ],
      },

      // ═══════════════════════════════════════════
      // SECTION 4: ACTIVE DIRECTORY ATTACKS
      // ═══════════════════════════════════════════
      {
        id: 'active-directory-attacks',
        title: 'Active Directory Attacks',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Active Directory (AD) is the identity backbone of most',
              'enterprises. If you control AD, you control everything:',
              'every user account, every computer, every server, every',
              'permission. It\'s the ultimate target.',
              '',
              '  KERBEROASTING',
              '    Any authenticated domain user can request a Kerberos',
              '    service ticket for any service with an SPN (Service',
              '    Principal Name). The ticket is encrypted with the',
              '    service account\'s NTLM hash. The attacker extracts',
              '    the ticket and cracks it offline.',
              '    If the service account password is weak (and service',
              '    account passwords are frequently weak or decades old),',
              '    the attacker gets those credentials.',
              '    Defense: long, random service account passwords. Managed',
              '    Service Accounts (gMSAs) rotate automatically.',
              '',
              '  AS-REP ROASTING',
              '    Targets accounts with "Do not require Kerberos',
              '    pre-authentication" enabled. The attacker requests an',
              '    Authentication Service Reply (AS-REP) and cracks the',
              '    encrypted portion offline. No authentication needed.',
              '    Same defense: strong passwords, disable the flag.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              '  GOLDEN TICKET',
              '    The attacker compromises the KRBTGT account — the',
              '    account that signs all Kerberos tickets in the domain.',
              '    With the KRBTGT hash, the attacker can forge a ticket',
              '    for any user, including Domain Admin, with any',
              '    permissions, for any duration. This is the master key.',
              '    It survives password resets for other accounts.',
              '    The only remediation: reset the KRBTGT password twice',
              '    (it keeps two hashes) and rebuild trust.',
              '',
              '  SILVER TICKET',
              '    Forged ticket for a specific service (SQL server, file',
              '    share, web app) using the service account\'s hash.',
              '    Narrower scope than Golden Ticket, but harder to detect',
              '    because the forged ticket never touches the domain',
              '    controller — it goes directly to the service.',
              '',
              '  BLOODHOUND — ATTACK PATH MAPPING',
              '    BloodHound collects Active Directory relationship data',
              '    and maps paths from any compromised user to Domain Admin.',
              '    "User A is local admin on Server B. Server B has a session',
              '    from Admin C. Admin C is in the Domain Admins group."',
              '    Three hops. Automated. Visual. Devastating.',
            ],
          },
          {
            type: 'guided-command',
            speaker: 'HANDLER',
            expectedCommand: 'ad query --domain=corp.local',
            commandPatterns: ['ad query --domain=corp.local', 'ad query --domain corp.local'],
            lines: [
              'Query the training domain. See what an attacker would see',
              'with basic domain user access.',
            ],
            commandOutput: `═══ ACTIVE DIRECTORY QUERY: corp.local ══════════════════

DOMAIN INFO:
  Domain: corp.local
  Forest: corp.local
  Domain Controllers: DC01.corp.local (10.10.1.1), DC02.corp.local (10.10.1.2)
  Functional Level: Windows Server 2016

KERBEROASTABLE ACCOUNTS (accounts with SPNs):
  svc_sql       SPN: MSSQLSvc/sql01.corp.local:1433   Password Age: 1,847 days !!
  svc_backup    SPN: host/backup01.corp.local          Password Age: 2,203 days !!
  svc_web       SPN: HTTP/portal.corp.local            Password Age: 412 days

AS-REP ROASTABLE ACCOUNTS (pre-auth disabled):
  t.legacy      Pre-auth disabled    Last logon: 847 days ago !!
  svc_monitor   Pre-auth disabled    Password Age: 1,102 days !!

PRIVILEGED GROUPS:
  Domain Admins (4 members): Administrator, j.garcia, s.chen, svc_deploy
  Enterprise Admins (1 member): Administrator

ATTACK PATHS (BloodHound):
  Path 1: Any User → Kerberoast svc_sql → svc_sql is local admin on SQL01
           → SQL01 has session from j.garcia (Domain Admin) → Domain Admin
  Path 2: Any User → AS-REP Roast svc_monitor → svc_monitor can read
           LAPS passwords → Local admin on DC01 → Domain Admin

CRITICAL FINDINGS:
  - 2 service accounts with passwords older than 5 years
  - 2 accounts with Kerberos pre-auth disabled
  - Service account svc_deploy is Domain Admin (should never be)
  - 2 clear attack paths from any user to Domain Admin`,
            explanation: [
              'This is what any authenticated user can enumerate with',
              'standard tools. No exploits, no special privileges. Just',
              'LDAP queries that Active Directory answers by design.',
              '',
              'Two clear paths to Domain Admin:',
              '',
              'Path 1 — Kerberoast svc_sql (password is 5 years old and',
              'likely crackable), use its local admin access on the SQL',
              'server, harvest the domain admin\'s cached credentials.',
              '',
              'Path 2 — AS-REP roast svc_monitor, use its LAPS read access',
              'to get the local admin password on the domain controller.',
              '',
              'Both paths require only a single domain user account to start.',
              'This is why AD hardening is critical — and why regular attack',
              'path analysis should be part of every security program.',
            ],
            hintOnWrong: 'Type: ad query --domain=corp.local',
          },
          {
            type: 'quiz',
            speaker: 'HANDLER',
            lines: [
              'An attacker has compromised the KRBTGT account hash in',
              'your domain. They are now generating Golden Tickets.',
              'You reset every user password in the domain, including',
              'all admin accounts.',
            ],
            question: 'Is the threat neutralized?',
            options: [
              { id: 'correct', text: 'No — Golden Tickets are signed by KRBTGT, not user accounts. The KRBTGT hash must be reset twice to invalidate all forged tickets.', correct: true },
              { id: 'wrong-yes', text: 'Yes — resetting all passwords invalidates all tickets', correct: false },
              { id: 'wrong-partial', text: 'Partially — the attacker can still use Silver Tickets but not Golden Tickets', correct: false },
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Correct. A Golden Ticket attack persists until the KRBTGT',
              'account is reset twice — because AD retains the current and',
              'previous password hash for KRBTGT. Reset it once, the old',
              'hash is still valid. Reset it twice, both hashes are new.',
              '',
              'This is one of the most difficult incidents to fully',
              'remediate. Organizations that discover Golden Ticket activity',
              'often need to rebuild their entire Active Directory forest.',
              '',
              'This chapter covered the red team lifecycle: initial access,',
              'post-exploitation, and the Active Directory attack surface.',
              'Next: we go deeper into stealth. How do adversaries stay',
              'hidden for months inside a network?',
            ],
          },
        ],
      },
    ],
  };
}
