import type { OrientationChapter } from './index.js';

export function getChapter09(): OrientationChapter {
  return {
    id: 'ch09-invisible',
    number: 9,
    title: 'Invisible Enemies',
    subtitle: 'APTs, Evasion, and Stealth',
    clearanceLevel: 'LEVEL 2 — CLASSIFIED',
    tier: 3,
    estimatedMinutes: 35,
    sections: [
      // ═══════════════════════════════════════════
      // SECTION 1: ADVANCED PERSISTENT THREATS
      // ═══════════════════════════════════════════
      {
        id: 'advanced-persistent-threats',
        title: 'Advanced Persistent Threats',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Everything you\'ve studied so far — phishing, injection,',
              'lateral movement, AD attacks — those are tools. Techniques.',
              'An Advanced Persistent Threat is the adversary who chains',
              'all of them together over months or years with a specific',
              'strategic objective.',
              '',
              'Three words. Each matters.',
              '',
              '  ADVANCED',
              '    Custom tooling. Zero-day exploits. Operational security',
              '    that rivals intelligence agencies. These adversaries',
              '    don\'t use off-the-shelf malware that triggers antivirus.',
              '    They build bespoke tools for each target.',
              '',
              '  PERSISTENT',
              '    They don\'t breach and run. They establish long-term',
              '    access — multiple redundant backdoors, persistence',
              '    mechanisms across different hosts, contingency C2',
              '    channels. If you close one door, they enter through',
              '    another. Median dwell time for APTs: 21 days. Top-tier',
              '    groups have maintained access for years.',
              '',
              '  THREAT',
              '    They have intent. Nation-state espionage, intellectual',
              '    property theft, critical infrastructure sabotage.',
              '    Not opportunistic. Targeted. Funded. Patient.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Real APT groups and their operational signatures:',
              '',
              '  APT29 (Cozy Bear / The Dukes) — Russian SVR',
              '    Known for: stealthy, long-duration intelligence',
              '    collection. SolarWinds supply chain attack. Custom',
              '    implants that communicate via cloud services (Azure,',
              '    AWS) to blend with legitimate traffic.',
              '',
              '  APT28 (Fancy Bear) — Russian GRU',
              '    Known for: aggressive operations targeting government,',
              '    military, and media. Phishing with weaponized documents,',
              '    zero-day exploits, credential harvesting. DNC breach.',
              '',
              '  APT41 (Double Dragon) — Chinese MSS-affiliated',
              '    Known for: dual-purpose operations — state-sponsored',
              '    espionage AND financially motivated cybercrime. Supply',
              '    chain compromises. Gaming industry targeting.',
              '',
              '  LAZARUS GROUP — North Korean RGB',
              '    Known for: financial theft to fund state operations.',
              '    SWIFT banking attacks. Cryptocurrency exchange heists.',
              '    Destructive attacks (Sony Pictures). WannaCry ransomware.',
              '',
              'Each group has distinct TTPs — Tactics, Techniques, and',
              'Procedures. Learning to attribute an intrusion based on',
              'TTPs is an advanced skill. We start with the tools they use.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Dwell time — the silent metric.',
              '',
              'Dwell time is the gap between initial compromise and',
              'detection. The global median has improved — but "improved"',
              'still means weeks in many environments. Some intrusions',
              'go undetected for months.',
              '',
              'What an APT does during dwell time:',
              '',
              '  WEEK 1    — Establish foothold. Install persistence.',
              '               Map the network. Identify high-value targets.',
              '  WEEKS 2-4 — Lateral movement. Escalate privileges.',
              '               Compromise additional credentials.',
              '               Establish backup C2 channels.',
              '  MONTHS 2+ — Systematic data collection. Email monitoring.',
              '               Document theft. Intellectual property exfiltration.',
              '               Monitoring communications for counter-intel.',
              '',
              'By the time you detect them, they\'ve already achieved',
              'their primary objectives. Detection at week 1 is the goal.',
              'Detection at month 3 is damage control.',
            ],
          },
        ],
      },

      // ═══════════════════════════════════════════
      // SECTION 2: EVASION TECHNIQUES
      // ═══════════════════════════════════════════
      {
        id: 'evasion-techniques',
        title: 'Evasion Techniques',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'APTs persist because they evade detection. Understanding',
              'evasion is understanding why your defenses have blind spots.',
              '',
              '  ANTIVIRUS EVASION',
              '',
              '    OBFUSCATION',
              '      Modifying malware to change its signature without',
              '      changing its function. String encoding, variable',
              '      renaming, code restructuring, encryption with runtime',
              '      decryption. Every modification produces a new hash',
              '      that doesn\'t match AV signature databases.',
              '',
              '    CUSTOM DROPPERS',
              '      Purpose-built loaders that download and execute the',
              '      real payload only after verifying the target environment.',
              '      The dropper itself contains no malicious functionality',
              '      — it just fetches the payload. If it detects a sandbox',
              '      (VM artifacts, analysis tools, timing anomalies), it',
              '      does nothing.',
              '',
              '    FILELESS MALWARE',
              '      Executes entirely in memory. No file written to disk.',
              '      Lives in PowerShell, WMI subscriptions, or .NET',
              '      assemblies loaded reflectively. Traditional AV scans',
              '      files on disk — if there\'s no file, there\'s nothing',
              '      to scan. EDR solutions with memory scanning address',
              '      this, but coverage is still incomplete.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              '  NETWORK EVASION',
              '',
              '    ENCRYPTED C2',
              '      All C2 traffic over HTTPS (port 443). Indistinguishable',
              '      from normal web browsing without TLS inspection.',
              '      Many organizations don\'t inspect TLS — it breaks',
              '      certificate pinning and raises privacy concerns.',
              '',
              '    DOMAIN FRONTING',
              '      The C2 traffic appears to go to a legitimate CDN',
              '      (cloudfront.net, azureedge.net). The actual destination',
              '      is hidden in the encrypted Host header. Network-level',
              '      inspection sees traffic to a trusted CDN. The CDN routes',
              '      it to the attacker\'s server. Major cloud providers have',
              '      restricted this, but variants persist.',
              '',
              '    DNS TUNNELING',
              '      Data encoded in DNS queries. "aGVsbG8gd29ybGQ.evil.com"',
              '      — the subdomain is the data. DNS is rarely blocked or',
              '      closely inspected. A slow but reliable exfiltration channel.',
              '',
              '  APPLICATION WHITELISTING BYPASS',
              '    Trusted binaries that execute arbitrary code:',
              '    mshta.exe, certutil.exe, msbuild.exe, installutil.exe,',
              '    regsvr32.exe. All signed by Microsoft. All capable of',
              '    running attacker-supplied code. Whitelisting them is',
              '    necessary for system function. Exploiting them is trivial.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              '  POWERSHELL OBFUSCATION',
              '    PowerShell is both essential for administration and',
              '    the most abused tool in post-exploitation. Obfuscation',
              '    makes malicious PowerShell difficult to detect:',
              '',
              '    STRING CONCATENATION',
              '      "Invoke"+"-Mimikatz" → Invoke-Mimikatz',
              '      Bypasses simple string matching.',
              '',
              '    ENCODING',
              '      -EncodedCommand accepts Base64-encoded scripts.',
              '      powershell -enc SQBuAHYAbwBrAGUALQBNAGkAbQBpAGsAYQB0AHoA',
              '      Hides the actual commands from command-line logging.',
              '',
              '    VARIABLE SUBSTITUTION',
              '      $a="Inv"; $b="oke-M"; $c="imi"; $d="katz"; &($a+$b+$c+$d)',
              '      No single string contains the tool name.',
              '',
              '    AMSI BYPASS',
              '      Anti-Malware Scan Interface inspects PowerShell scripts',
              '      at runtime. Attackers patch AMSI in memory before running',
              '      their payload, blinding the scanner.',
              '',
              '    Detection: Script Block Logging and Module Logging capture',
              '    the deobfuscated version of PowerShell commands. Enable',
              '    both. Always.',
            ],
          },
          {
            type: 'guided-command',
            speaker: 'HANDLER',
            expectedCommand: 'logs show --source=endpoint --type=suspicious',
            commandPatterns: ['logs show --source=endpoint --type=suspicious', 'logs show --source=endpoint'],
            lines: [
              'Examine endpoint detection logs. Look for evasion indicators.',
            ],
            commandOutput: `═══ ENDPOINT DETECTION LOGS (suspicious activity) ══════

[08:14:22] HOST: WS-FINANCE-04
  Process: powershell.exe -enc SQBuAHYAbwBrAGUALQBXAGUAYgBSAGUAcQB1AGUAcwB0AC...
  Parent: winword.exe (PID 3844)
  !! ALERT: Encoded PowerShell spawned from Office application !!

[08:14:24] HOST: WS-FINANCE-04
  Network: powershell.exe → 104.18.32.7:443 (HTTPS)
  DNS: update-service.azureedge.net
  !! ALERT: Possible domain fronting — Azure CDN endpoint !!

[08:14:26] HOST: WS-FINANCE-04
  Process: powershell.exe loaded .NET assembly into memory (no disk write)
  Memory: Reflective PE injection detected
  !! ALERT: Fileless payload — in-memory execution !!

[08:15:01] HOST: WS-FINANCE-04
  Process: powershell.exe accessed lsass.exe (PID 684)
  Method: MiniDumpWriteDump via comsvcs.dll
  !! CRITICAL: LSASS credential dumping via LOL binary !!

[08:15:03] HOST: WS-FINANCE-04
  AMSI: Scan interface returned null (expected object)
  !! ALERT: AMSI may have been patched in-process !!

TIMELINE: Word macro → encoded PowerShell → domain fronting C2 →
          fileless payload → AMSI bypass → LSASS dump
          Total elapsed: 41 seconds`,
            explanation: [
              'Five evasion techniques in 41 seconds:',
              '',
              '1. Encoded PowerShell — hides commands from basic logging',
              '2. Domain fronting — C2 traffic looks like Azure CDN',
              '3. Fileless execution — no malware on disk for AV to scan',
              '4. AMSI bypass — blinded the runtime script scanner',
              '5. LOL credential dump — used comsvcs.dll (a legitimate',
              '   Windows DLL) to dump LSASS instead of Mimikatz',
              '',
              'Each technique individually might evade detection. Combined,',
              'they create a chain that\'s very difficult for legacy security',
              'tools to catch. Modern EDR with behavioral analysis is the',
              'answer — not signature-based detection.',
              '',
              'The Word macro as the initial trigger is the weakest link',
              'in the chain. Block macros from the internet, and this entire',
              'attack sequence never starts.',
            ],
            hintOnWrong: 'Type: logs show --source=endpoint --type=suspicious',
          },
        ],
      },

      // ═══════════════════════════════════════════
      // SECTION 3: SIDE CHANNELS AND COVERT COMMUNICATION
      // ═══════════════════════════════════════════
      {
        id: 'covert-channels',
        title: 'Side Channels and Covert Communication',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'When standard communication channels are monitored, APTs',
              'use covert channels — methods of transmitting data through',
              'mechanisms not designed for communication.',
              '',
              '  TIMING ATTACKS',
              '    Information encoded in the timing of events rather',
              '    than their content. A process that takes 100ms to',
              '    respond means "1." A process that takes 200ms means "0."',
              '    No data payload to inspect. The information is in the',
              '    gaps between packets.',
              '    Application: blind SQL injection uses timing to extract',
              '    data one bit at a time. If the query is true, the server',
              '    responds in 50ms. If false, 5 seconds (injected SLEEP).',
              '',
              '  COVERT CHANNELS IN PROTOCOLS',
              '    Data hidden in unused or optional protocol fields.',
              '    TCP ISN (Initial Sequence Number) — should be random,',
              '    can be used to encode 32 bits per connection.',
              '    IP TTL field — slight variations encode data.',
              '    HTTP headers — custom headers or values in standard',
              '    headers carry hidden messages.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              '  STEGANOGRAPHY',
              '    Hiding data inside other data. The cover medium looks',
              '    normal to the naked eye.',
              '    IMAGE STEGO — data encoded in least-significant bits',
              '    of pixel values. A 1920x1080 image has 6.2 million',
              '    pixels. Modifying the last bit of each channel is',
              '    visually imperceptible but stores 2.3MB of data.',
              '    AUDIO STEGO — data in ultrasonic frequencies or',
              '    least-significant bits of audio samples.',
              '    DOCUMENT STEGO — data in whitespace, font variations,',
              '    or metadata fields.',
              '    Detection: statistical analysis of the cover medium.',
              '    Modified images have detectable entropy changes.',
              '',
              '  ICMP TUNNELING',
              '    Data encoded in ICMP echo request/reply payloads.',
              '    Ping is allowed through most firewalls. The data field',
              '    of an ICMP packet can carry arbitrary content.',
              '    Tools: icmpsh, ICMP C2 channels.',
              '    Detection: ICMP packets with unusually large payloads',
              '    or high frequency from a single host.',
            ],
          },
          {
            type: 'quiz',
            speaker: 'HANDLER',
            lines: [
              'Your network monitoring detects the following anomaly:',
              '  - A single workstation is sending 500+ ICMP echo requests',
              '    per minute to an external IP',
              '  - Each ICMP packet has a payload of 1,400 bytes',
              '    (normal ping: 32-64 bytes)',
              '  - The external IP belongs to a VPS provider in a country',
              '    with no business relationship to the organization',
            ],
            question: 'What is the most likely explanation?',
            options: [
              { id: 'correct', text: 'ICMP tunneling — data exfiltration through oversized ICMP payloads to an external C2 server', correct: true },
              { id: 'ddos', text: 'DDoS attack — the workstation is participating in a ping flood', correct: false },
              { id: 'diag', text: 'Network diagnostic — an administrator running extended ping tests', correct: false },
              { id: 'vpn', text: 'VPN misconfiguration — ICMP traffic is being routed incorrectly', correct: false },
            ],
          },
        ],
      },

      // ═══════════════════════════════════════════
      // SECTION 4: THREAT HUNTING
      // ═══════════════════════════════════════════
      {
        id: 'threat-hunting',
        title: 'Threat Hunting',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Traditional security is reactive — wait for an alert, then',
              'investigate. Threat hunting is proactive — assume the',
              'adversary is already inside and go find them.',
              '',
              'The difference matters. Alerts catch known patterns.',
              'Hunting finds unknown threats — the APTs that evaded',
              'every automated detection you have.',
              '',
              'The methodology:',
              '',
              '  1. HYPOTHESIS',
              '     Start with a testable assumption based on threat',
              '     intelligence, TTPs, or environmental knowledge.',
              '     "If APT29 targeted us, they would likely use phishing',
              '     to gain initial access and PowerShell for post-exploitation."',
              '',
              '  2. DATA COLLECTION',
              '     Gather the relevant logs: endpoint telemetry, network',
              '     flows, DNS queries, authentication events, process',
              '     creation events.',
              '',
              '  3. INVESTIGATION',
              '     Search for evidence that supports or refutes the',
              '     hypothesis. Anomalies. Outliers. Things that don\'t fit.',
              '',
              '  4. RESOLUTION',
              '     Confirm or deny the hypothesis. If confirmed, escalate.',
              '     If denied, refine the hypothesis and hunt again.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Key hunting techniques:',
              '',
              '  STACK COUNTING',
              '    Count occurrences of values across your environment.',
              '    If 10,000 workstations run 50 unique scheduled tasks,',
              '    but one workstation has a scheduled task that exists',
              '    nowhere else — investigate. Rarity equals suspicion.',
              '',
              '  FREQUENCY ANALYSIS',
              '    Look for regular, periodic connections. Beaconing.',
              '    Sort network connections by interval consistency.',
              '    Legitimate traffic is irregular. C2 is periodic.',
              '',
              '  LONG-TAIL ANALYSIS',
              '    Most DNS queries go to popular domains. The long tail',
              '    — domains queried by only one host — contains C2',
              '    infrastructure, DGA domains, and exfiltration channels.',
              '',
              '  PROCESS LINEAGE',
              '    Track parent-child process relationships.',
              '    winword.exe → cmd.exe → powershell.exe is suspicious.',
              '    svchost.exe spawning PowerShell is suspicious.',
              '    explorer.exe spawning certutil.exe is suspicious.',
              '    Normal process trees have predictable lineage.',
            ],
          },
          {
            type: 'scenario',
            speaker: 'HANDLER',
            scenarioContext: 'The Observer is tasked with hunting for APT indicators in an environment where no alerts have been triggered. The Handler provides guidance on what traces an APT would leave.',
            lines: [
              'Scenario. Proactive hunt — no alerts to start from.',
              '',
              'A DI7 client in the defense sector has requested a threat',
              'hunt. No incidents detected. No alerts triggered. But their',
              'threat intelligence team received reporting that APT groups',
              'are targeting their industry vertical.',
              '',
              'If an APT is here, what traces would they leave?',
              '',
              'You begin with hypothesis: "An APT with initial access',
              'has established persistence and is conducting reconnaissance',
              'or data staging for exfiltration."',
              '',
              'Your hunt across 90 days of telemetry reveals:',
              '',
              '  FINDING 1: One workstation (WS-ENG-17) has a scheduled',
              '    task named "WindowsUpdateCheck" that runs a PowerShell',
              '    script from C:\\ProgramData\\Update\\check.ps1 every 4 hours.',
              '    No other workstation has this task. The script was created',
              '    68 days ago.',
              '',
              '  FINDING 2: WS-ENG-17 makes DNS queries to a domain',
              '    (cdn-sync-update.com) that no other host in the',
              '    environment queries. The queries occur at intervals',
              '    of approximately 240 minutes with ±30 second jitter.',
              '',
              '  FINDING 3: The user of WS-ENG-17 is a senior engineer',
              '    with access to classified defense project files.',
              '    SIEM shows no anomalous authentication events for',
              '    this user — all logins from expected locations.',
            ],
          },
          {
            type: 'decision',
            speaker: 'HANDLER',
            lines: [
              'Three findings. No alerts ever triggered on any of them.',
              'The scheduled task looks like a Windows update. The DNS',
              'queries look like CDN traffic. The user\'s behavior appears',
              'normal.',
              '',
              'But stack counting flagged the unique scheduled task.',
              'Long-tail analysis flagged the unique DNS domain. And the',
              'timing analysis shows beaconing with jitter — every 240',
              'minutes, ±30 seconds. That\'s not human behavior. That\'s',
              'malware with an anti-detection interval.',
              '',
              'What\'s your assessment?',
            ],
            question: 'How do you classify these findings?',
            options: [
              {
                id: 'apt-confirmed',
                text: 'Probable APT compromise — the combination of unique persistence, unique C2 domain, beaconing with jitter, and high-value target strongly indicates a long-term intrusion',
                correct: true,
              },
              {
                id: 'inconclusive',
                text: 'Inconclusive — these could be legitimate scheduled tasks and normal DNS traffic',
                correct: false,
              },
              {
                id: 'false-positive',
                text: 'Likely false positive — the user has no anomalous login behavior, so their workstation is probably clean',
                correct: false,
              },
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Probable APT compromise. The indicators are individually',
              'subtle — that\'s by design. APTs don\'t trigger alerts.',
              'But the convergence of evidence is compelling:',
              '',
              '  - A unique scheduled task that exists on one machine in',
              '    the entire enterprise (stack counting anomaly)',
              '  - A DNS domain queried by one host only (long-tail anomaly)',
              '  - Beaconing with jitter at 240-minute intervals',
              '    (frequency analysis anomaly)',
              '  - 68 days of persistence (dwell time consistent with APT)',
              '  - The targeted host belongs to a cleared engineer with',
              '    access to defense projects (high-value target selection)',
              '',
              'No single finding would justify an incident declaration.',
              'Together, they paint a clear picture.',
              '',
              'The user\'s "normal" login behavior is expected — the APT',
              'compromised the workstation, not the user\'s credentials.',
              'The user logs in normally. The malware operates independently.',
              'This is why credential-focused monitoring alone is insufficient.',
              '',
              'This chapter covered the most sophisticated adversaries and',
              'their techniques. Stealth is their advantage. Systematic,',
              'hypothesis-driven hunting is yours. Tier 3 is complete.',
            ],
          },
        ],
      },
    ],
  };
}
