import type { OrientationChapter } from './index.js';

export function getChapter12(): OrientationChapter {
  return {
    id: 'ch12-edge',
    number: 12,
    title: 'The Edge',
    subtitle: 'Bleeding-Edge Threats, AI Security, and the Future',
    clearanceLevel: 'R1 — ADVANCED',
    tier: 4,
    estimatedMinutes: 30,
    sections: [
      // ═══════════════════════════════════════════
      // SECTION 1: AI-POWERED ATTACKS AND DEFENSES
      // ═══════════════════════════════════════════
      {
        id: 'ai-threats',
        title: 'AI-Powered Attacks and Defenses',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'The threat landscape just shifted. Again.',
              '',
              'Every tool we\'ve discussed — phishing, malware, social',
              'engineering, exploitation — is being augmented by artificial',
              'intelligence. Not in theory. Right now. In active operations',
              'DI7 is tracking.',
              '',
              '  LLM-GENERATED PHISHING',
              '    Forget broken English and obvious templates. Large language',
              '    models generate contextually perfect phishing emails in any',
              '    language, matching the target\'s communication style. They',
              '    can scrape a target\'s LinkedIn, publications, and public',
              '    emails, then craft a message indistinguishable from a',
              '    real colleague. The detection signals we relied on —',
              '    poor grammar, generic greetings, urgency markers — are',
              '    vanishing.',
              '',
              '  DEEPFAKES FOR SOCIAL ENGINEERING',
              '    Real-time voice cloning. Video deepfakes for video calls.',
              '    In 2024, a finance worker transferred $25M after a video',
              '    call with what appeared to be the CFO and colleagues.',
              '    Every person on the call was AI-generated.',
              '    Voice verification is no longer reliable. Video calls',
              '    are no longer proof of identity.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              '  AI-POWERED POLYMORPHIC MALWARE',
              '    Traditional malware has a signature — a unique pattern',
              '    that antivirus can detect. AI-assisted malware rewrites',
              '    itself on every execution. Different code structure,',
              '    different evasion techniques, same payload. Each',
              '    instance is unique. Signature-based detection fails.',
              '',
              '    The malware can also use LLMs to generate new evasion',
              '    techniques, analyze the target environment, and adapt',
              '    its behavior to avoid specific security tools.',
              '',
              '  DEFENSIVE AI',
              '    The same technology serves defense:',
              '    - Behavioral analysis — establish baselines for user and',
              '      network behavior, flag deviations in real-time.',
              '      Catches insider threats and compromised accounts.',
              '    - Anomaly detection — identify patterns across billions',
              '      of events that no human analyst could process.',
              '    - Automated response — containment actions triggered in',
              '      milliseconds when threat patterns are detected.',
              '      Isolate a host, revoke credentials, block an IP.',
              '    - Threat intelligence correlation — connect indicators',
              '      across global feeds faster than any SOC team.',
              '',
              'The arms race between offensive and defensive AI is the',
              'defining challenge of modern cybersecurity.',
            ],
          },
          {
            type: 'quiz',
            speaker: 'HANDLER',
            lines: [
              'DI7 intercepts an email that perfectly mimics the writing',
              'style of a company\'s CEO, references a real internal project',
              'by its codename, and includes details from a meeting that',
              'occurred yesterday. The email requests an urgent wire transfer.',
              'The CEO\'s email account shows no signs of compromise.',
            ],
            question: 'What is the most likely attack vector?',
            options: [
              { id: 'ai-phish', text: 'LLM-generated spear phishing — AI synthesized public/leaked information to craft a contextually perfect message', correct: true },
              { id: 'insider', text: 'Insider threat — someone with access to the meeting shared details', correct: false },
              { id: 'email', text: 'Email account compromise — the CEO\'s account was accessed and restored before detection', correct: false },
              { id: 'template', text: 'Traditional spear phishing — a well-researched manual operation', correct: false },
            ],
          },
        ],
      },

      // ═══════════════════════════════════════════
      // SECTION 2: RANSOMWARE EVOLUTION
      // ═══════════════════════════════════════════
      {
        id: 'ransomware-evolution',
        title: 'Ransomware Evolution',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Ransomware has evolved from nuisance to existential threat.',
              '',
              '  DOUBLE EXTORTION',
              '    Phase 1: Encrypt the victim\'s data.',
              '    Phase 2: Threaten to publish the stolen data publicly.',
              '    Paying the ransom to decrypt is no longer enough.',
              '    Even with perfect backups, the data leak threat persists.',
              '',
              '  TRIPLE EXTORTION',
              '    All of the above, plus:',
              '    Phase 3: Contact the victim\'s customers, partners, or',
              '    regulators directly. "Your data is in our possession.',
              '    Your vendor refuses to pay. We\'re releasing it Tuesday."',
              '    Pressure from all directions simultaneously.',
              '',
              '  RANSOMWARE-AS-A-SERVICE (RaaS)',
              '    The ecosystem has professionalized. RaaS operators build',
              '    the platform: the malware, the payment portal, the',
              '    negotiation chat, the data leak site. Affiliates buy',
              '    access and conduct the actual intrusions. Revenue is',
              '    split — typically 70/30 or 80/20 in favor of the affiliate.',
              '    Some RaaS groups have HR, bug bounties, and customer service.',
            ],
          },
          {
            type: 'scenario',
            speaker: 'HANDLER',
            scenarioContext: 'A regional hospital network has been hit by ransomware. 14 hospitals, patient care systems offline, data exfiltrated. The ransom demand is $12M in Bitcoin. You are the DI7 advisor on-scene.',
            lines: [
              'Scenario. Full ransomware incident response.',
              '',
              'SITUATION: MedCore Health — 14-hospital regional network.',
              'At 02:47 this morning, the Nightfall ransomware group',
              'encrypted MedCore\'s central EHR (Electronic Health Records)',
              'system, radiology imaging servers, and pharmacy dispensing',
              'systems. Patient care is degraded across all 14 facilities.',
              '',
              'The ransom note demands $12M in Bitcoin within 72 hours.',
              'Nightfall has published sample patient records on their',
              'leak site as proof of exfiltration. They claim to have',
              '4.2M patient records.',
              '',
              'You are DI7\'s advisor on-scene. The CEO, CISO, legal',
              'counsel, and the FBI liaison are in the room. They need',
              'your assessment.',
              '',
              'Key facts:',
              '  - Backups exist but were last tested 6 months ago',
              '  - Backup servers are on the same network (may be encrypted)',
              '  - Two hospitals have diverted ambulances to other facilities',
              '  - HIPAA requires notification within 60 days of discovery',
              '  - Cyber insurance policy has a $5M ransomware sublimit',
            ],
          },
          {
            type: 'decision',
            speaker: 'HANDLER',
            lines: [
              'The CEO asks you directly: "Should we pay?"',
              '',
              'The FBI liaison advises against payment. Legal counsel',
              'notes the regulatory exposure. The CISO reports that',
              'backup restoration could take 2-4 weeks if backups are',
              'intact. Patient safety is the immediate concern.',
            ],
            question: 'What is your recommendation?',
            options: [
              {
                id: 'no-pay-restore',
                text: 'Do not pay. Verify backup integrity immediately. Activate manual patient care procedures. Engage an incident response firm to contain, eradicate, and restore in parallel.',
                correct: true,
              },
              {
                id: 'pay',
                text: 'Pay the ransom. Patient safety is paramount and 2-4 weeks without EHR is unacceptable.',
                correct: false,
              },
              {
                id: 'negotiate',
                text: 'Open negotiation to buy time while quietly attempting restoration.',
                correct: false,
              },
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'The correct call is do not pay, with aggressive parallel',
              'workstreams.',
              '',
              'Why not pay: payment funds criminal enterprise, provides no',
              'guarantee of decryption, does NOT prevent data publication',
              '(many groups leak anyway), and may violate OFAC sanctions',
              'if the group is linked to sanctioned entities.',
              '',
              'Why not negotiate as primary strategy: it signals willingness',
              'to pay, and the attacker will exploit that leverage.',
              '',
              'The response plan:',
              '  1. CONTAIN — isolate affected systems, prevent further spread',
              '  2. ASSESS — verify backup integrity within hours, not days',
              '  3. OPERATE — activate paper/manual procedures for patient care',
              '  4. RESTORE — begin recovery from verified clean backups',
              '  5. NOTIFY — HIPAA notification clock is ticking; engage',
              '     regulators proactively',
              '  6. INVESTIGATE — determine initial access vector to prevent',
              '     re-compromise during recovery',
              '',
              'Patient safety is the priority. Manual care procedures are',
              'imperfect but functional. Hospitals operated without EHR',
              'systems for decades.',
            ],
          },
        ],
      },

      // ═══════════════════════════════════════════
      // SECTION 3: SUPPLY CHAIN AND ZERO-DAY
      // ═══════════════════════════════════════════
      {
        id: 'supply-chain-zeroday',
        title: 'Supply Chain and Zero-Day',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'The most devastating attacks of the last five years',
              'share a common thread: the supply chain.',
              '',
              '  SOLARWINDS (2020)',
              '    Nation-state actors compromised the build pipeline of',
              '    SolarWinds Orion — a network monitoring tool used by',
              '    18,000 organizations including Fortune 500 companies',
              '    and US government agencies. A malicious update was',
              '    signed with SolarWinds\' legitimate certificate and',
              '    distributed through their official update channel.',
              '    The compromised code (SUNBURST) sat dormant for 2 weeks',
              '    before activating. Dwell time before detection: 9 months.',
              '',
              '  LOG4SHELL (2021)',
              '    A critical vulnerability in Log4j, a Java logging library',
              '    embedded in millions of applications. A single crafted',
              '    log message could achieve remote code execution.',
              '    The vulnerability existed for 8 years before discovery.',
              '    Affected: Minecraft servers to enterprise cloud platforms.',
              '    The lesson: a vulnerability in a foundational library',
              '    is a vulnerability in everything built on it.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              '  MOVEit (2023)',
              '    A zero-day SQL injection in MOVEit Transfer, a managed',
              '    file transfer product. The Cl0p ransomware group',
              '    exploited it to steal data from 2,500+ organizations.',
              '    Mass exploitation before the vendor knew the vulnerability',
              '    existed. No ransomware was deployed — pure data theft',
              '    and extortion.',
              '',
              '  THE ZERO-DAY ECONOMY',
              '    Zero-days — vulnerabilities unknown to the vendor — are',
              '    traded as commodities.',
              '    Government buyers pay $500K-$2M for high-value zero-days.',
              '    Brokers like Zerodium publish price lists openly.',
              '    iOS full-chain zero-click: up to $2M.',
              '    Chrome RCE: up to $500K.',
              '    The market creates an incentive NOT to report vulnerabilities.',
              '',
              '  VULNERABILITY MANAGEMENT AT SCALE',
              '    Prioritization is everything. Not every CVE matters to',
              '    your environment. EPSS (Exploit Prediction Scoring System)',
              '    estimates the probability of exploitation. CISA KEV',
              '    (Known Exploited Vulnerabilities) catalogs confirmed',
              '    in-the-wild exploitation. Patch what\'s being exploited.',
              '    Then patch what\'s likely to be exploited. Then the rest.',
            ],
          },
          {
            type: 'quiz',
            speaker: 'HANDLER',
            lines: [
              'Your organization uses a commercial VPN appliance. A zero-day',
              'vulnerability is published with a CVSS score of 9.8 and CISA',
              'adds it to the KEV catalog the same day. A proof-of-concept',
              'exploit is circulating on social media.',
            ],
            question: 'What is the appropriate response timeline?',
            options: [
              { id: 'immediate', text: 'Emergency patching within hours — take the VPN offline if needed. KEV + active exploitation demands immediate action.', correct: true },
              { id: 'week', text: 'Patch within the standard 7-day window for critical vulnerabilities', correct: false },
              { id: 'test', text: 'Test the patch in staging for 2 weeks before production deployment', correct: false },
              { id: 'monitor', text: 'Monitor for exploitation attempts and patch at the next maintenance window', correct: false },
            ],
          },
        ],
      },

      // ═══════════════════════════════════════════
      // SECTION 4: THE FUTURE & GRADUATION
      // ═══════════════════════════════════════════
      {
        id: 'future-graduation',
        title: 'The Future & Graduation',
        steps: [
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'What\'s coming. The threats DI7 is preparing for now.',
              '',
              '  QUANTUM THREATS TO CRYPTOGRAPHY',
              '    Quantum computers will break RSA, ECC, and Diffie-Hellman.',
              '    Shor\'s algorithm factors large numbers efficiently —',
              '    destroying the mathematical foundation of asymmetric crypto.',
              '    Timeline: estimates range from 5 to 15 years for',
              '    cryptographically relevant quantum computers.',
              '',
              '    "Harvest now, decrypt later" — adversaries are collecting',
              '    encrypted data TODAY, storing it, and waiting for quantum',
              '    capability to decrypt it. If the data has long-term value',
              '    (state secrets, medical records, intellectual property),',
              '    the window of vulnerability is NOW, not when quantum arrives.',
              '',
              '  POST-QUANTUM CRYPTOGRAPHY (PQC)',
              '    NIST finalized PQC standards in 2024:',
              '    ML-KEM (CRYSTALS-Kyber) — key encapsulation / key exchange',
              '    ML-DSA (CRYSTALS-Dilithium) — digital signatures',
              '    SLH-DSA (SPHINCS+) — stateless hash-based signatures',
              '    Migration is underway. TLS, VPNs, PKI, code signing —',
              '    everything that uses asymmetric crypto must transition.',
              '    This is a multi-year, infrastructure-wide effort.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              '  IoT/OT CONVERGENCE',
              '    Operational technology (power grids, water treatment,',
              '    manufacturing) was never designed for connectivity. It\'s',
              '    now connected. Industrial control systems running 20-year-old',
              '    software, accessible via the internet, with default',
              '    credentials. The Colonial Pipeline attack (2021) shut down',
              '    fuel distribution for the US East Coast. A VPN credential',
              '    was the entry point.',
              '',
              '    Smart buildings, medical devices, autonomous vehicles —',
              '    every connected device is an endpoint. Every endpoint',
              '    is an attack surface. The number of IoT devices is',
              '    projected to exceed 30 billion by 2030.',
              '',
              'The threats are evolving faster than defenses. AI accelerates',
              'both sides. Quantum threatens the cryptographic foundation.',
              'Supply chains create cascading single points of failure.',
              'The convergence of IT and OT means cyber attacks have',
              'physical consequences.',
              '',
              'This is the world you\'re operating in, Observer.',
            ],
          },
          {
            type: 'decision',
            speaker: 'HANDLER',
            scenarioContext: 'Final strategic decision. A critical infrastructure operator faces a complex threat requiring synthesis of all orientation material.',
            lines: [
              'Final assessment. This is everything you\'ve learned.',
              '',
              'SITUATION: NorthGrid Energy — regional power utility serving',
              '2.8M customers. Their CISO presents DI7 with the following:',
              '',
              '  - Threat intelligence indicates a nation-state group is',
              '    actively targeting their sector',
              '  - SCADA systems run legacy protocols with no encryption',
              '  - IT and OT networks were recently converged to reduce costs',
              '  - A third-party vendor has persistent VPN access for',
              '    maintenance with shared credentials (not rotated in 2 years)',
              '  - Cloud migration in progress — half the IT workload is',
              '    now in AWS, other half on-premises',
              '  - Security team of 8 people, no 24/7 SOC coverage',
              '  - Budget for one major security initiative this fiscal year',
              '',
              'The CISO asks: "Where do we start?"',
            ],
            question: 'What is the single highest-impact security initiative for NorthGrid?',
            options: [
              {
                id: 'segment',
                text: 'Immediately re-segment IT and OT networks with strict access controls, eliminate the shared vendor credentials, and deploy network monitoring at the IT/OT boundary',
                correct: true,
              },
              {
                id: 'soc',
                text: 'Build a 24/7 SOC with AI-powered threat detection across all environments',
                correct: false,
              },
              {
                id: 'cloud',
                text: 'Accelerate the cloud migration and implement Zero Trust architecture for all cloud workloads',
                correct: false,
              },
              {
                id: 'pqc',
                text: 'Begin post-quantum cryptography migration to protect SCADA communications',
                correct: false,
              },
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Correct. Network segmentation between IT and OT is the',
              'existential priority.',
              '',
              'A converged IT/OT network with a nation-state adversary',
              'actively targeting the sector means that any IT compromise',
              '— a phished employee, a compromised cloud workload, that',
              'shared vendor VPN credential — gives the attacker a direct',
              'path to SCADA systems controlling physical infrastructure.',
              '',
              'The vendor\'s shared, unrotated VPN credential is the most',
              'likely initial access vector. Kill it today. Issue individual,',
              'time-limited credentials with MFA.',
              '',
              'A 24/7 SOC is important but takes 6-12 months to build',
              'and doesn\'t address the structural vulnerability. Cloud',
              'migration improvements matter but aren\'t the existential',
              'risk. Post-quantum migration is premature — SCADA systems',
              'need basic encryption first, not next-generation crypto.',
              '',
              'Prioritization under constraints is the hardest skill in',
              'this field. You just demonstrated it.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'HANDLER',
            lines: [
              'Observer.',
              '',
              'Twelve chapters. The digital battlefield, the terminal,',
              'your first investigation, authentication, network defense,',
              'social engineering, web vulnerabilities, perimeter breaches,',
              'stealth adversaries, cryptography, cloud architecture, and',
              'now — the bleeding edge.',
              '',
              'You\'ve earned what comes next.',
              '',
              'I\'m handing you to Director Vasquez.',
            ],
          },
          {
            type: 'narrative',
            speaker: 'DIRECTOR VASQUEZ',
            lines: [
              'Observer.',
              '',
              'You have completed the New Observer Orientation Program.',
              'Your clearance is now R1 — Advanced Operations.',
              '',
              'You have demonstrated the breadth and depth of understanding',
              'that DI7 requires of its field operatives. The threats you',
              'will face are real, evolving, and consequential.',
              '',
              'Your Handler will continue to brief you on active operations.',
              'The Operations Center is expecting you.',
              '',
              'Welcome to DI7, Observer. Formally.',
            ],
          },
        ],
      },
    ],
  };
}
