import React, { useState } from 'react';
import { Box, Text, useInput } from 'ink';
import { colors } from '../theme.js';
import { useGameStore } from '../../engine/state.js';

const GUIDE_LINES = [
  '╔══════════════════════════════════════════════════════════════════════╗',
  '║            O M N I U S  —  P R O D U C T   G U I D E              ║',
  '║                    DI7 Data Intelligence Division                   ║',
  '╠══════════════════════════════════════════════════════════════════════╣',
  '║                                                                    ║',
  '║  ─── WHAT IS OMNIUS? ───                                           ║',
  '║                                                                    ║',
  '║  Omnius is a terminal-based interactive cybersecurity training      ║',
  '║  game disguised as an espionage thriller. Players take the role     ║',
  '║  of a new "Observer" recruited into DI7 — a fictional covert       ║',
  '║  cyber intelligence division.                                      ║',
  '║                                                                    ║',
  '║  The game teaches real cybersecurity concepts through interactive   ║',
  '║  scenarios where players type simulated security commands,          ║',
  '║  investigate incidents, and make consequential decisions.           ║',
  '║                                                                    ║',
  '║  Underneath the narrative, the game silently captures behavioral    ║',
  '║  data that can be used as ML features to predict cybersecurity      ║',
  '║  aptitude and likelihood of program completion.                     ║',
  '║                                                                    ║',
  '║  ─── INSTALLATION ───                                              ║',
  '║                                                                    ║',
  '║  Requirements: Node.js 20+, a terminal with ANSI color support     ║',
  '║  Recommended terminal size: 120×40 or larger                       ║',
  '║                                                                    ║',
  '║  Install & run (no install needed):                                ║',
  '║    $ npx omnius                                                    ║',
  '║                                                                    ║',
  '║  Or install globally:                                              ║',
  '║    $ npm install -g omnius                                         ║',
  '║    $ omnius                                                        ║',
  '║                                                                    ║',
  '║  From source:                                                      ║',
  '║    $ git clone <repo-url>                                          ║',
  '║    $ cd Omnius && pnpm install && pnpm dev                         ║',
  '║                                                                    ║',
  '║  ─── HOW TO PLAY ───                                               ║',
  '║                                                                    ║',
  '║  1. Launch the game. You will see the title screen with a          ║',
  '║     Braille art silhouette and the OMNIUS logo.                    ║',
  '║  2. Select "NEW OPERATION" to begin.                               ║',
  '║  3. You enter the New Observer Orientation Program — a 12-chapter  ║',
  '║     interactive cybersecurity curriculum.                           ║',
  '║  4. Each chapter has narrative briefings, guided commands, quizzes, ║',
  '║     scenarios, and decision points.                                ║',
  '║  5. After completing Chapters 1-3 (Tier 1), field missions unlock. ║',
  '║  6. Missions are self-contained cybersecurity incidents where you   ║',
  '║     type commands, investigate, and make decisions.                 ║',
  '║  7. After completing all 12 chapters, you receive R1 clearance.    ║',
  '║                                                                    ║',
  '║  ─── CHARACTERS ───                                                ║',
  '║                                                                    ║',
  '║  THE HANDLER   Your primary contact. Calm, professional, always    ║',
  '║                present. Briefs you, guides you, evaluates you.     ║',
  '║  OMNIUS        DI7\'s AI threat intelligence system. Delivers       ║',
  '║                data, alerts, and system outputs.                   ║',
  '║  DIR. VASQUEZ  Head of DI7. Appears at clearance transitions.     ║',
  '║  KAI TANAKA    Senior Observer. Peer mentor, hints when stuck.     ║',
  '║  REN           Red Team lead. Provides attacker perspective.       ║',
  '║                                                                    ║',
  '║  ─── THE 12-CHAPTER CURRICULUM ───                                 ║',
  '║                                                                    ║',
  '║  TIER 1: FOUNDATIONS (Clearance Level 0)                           ║',
  '║    Ch 01  The Digital Battlefield                                  ║',
  '║           CIA triad, threat actors, kill chain, MITRE ATT&CK      ║',
  '║    Ch 02  The Observer\'s Terminal                                   ║',
  '║           All 12 commands with guided practice                     ║',
  '║    Ch 03  First Blood                                              ║',
  '║           Guided phishing investigation with decisions             ║',
  '║                                                                    ║',
  '║  TIER 2: DEFENSIVE OPERATIONS (Clearance Level 1)                  ║',
  '║    Ch 04  Walls and Gates                                          ║',
  '║           Authentication, MFA, session management, access control  ║',
  '║    Ch 05  Reading the Wire                                         ║',
  '║           TCP/IP, firewalls, traffic analysis, lateral movement    ║',
  '║    Ch 06  The Human Factor                                         ║',
  '║           Social engineering, phishing anatomy, deception psych    ║',
  '║                                                                    ║',
  '║  TIER 3: OFFENSIVE AWARENESS (Clearance Level 2)                   ║',
  '║    Ch 07  The Web\'s Soft Underbelly                                 ║',
  '║           SQL injection, XSS, web app vulnerabilities              ║',
  '║    Ch 08  Breaching the Perimeter                                  ║',
  '║           Red team ops, post-exploitation, AD attacks              ║',
  '║    Ch 09  Invisible Enemies                                        ║',
  '║           APTs, evasion, fileless malware, threat hunting          ║',
  '║                                                                    ║',
  '║  TIER 4: ADVANCED OPERATIONS (Clearance R1)                        ║',
  '║    Ch 10  Crypto Wars                                              ║',
  '║           Cryptography, TLS, protocol failures                     ║',
  '║    Ch 11  Cloud Fortress                                           ║',
  '║           Cloud security, SSRF, DevSecOps, zero trust              ║',
  '║    Ch 12  The Edge                                                 ║',
  '║           AI threats, ransomware IR, supply chain, graduation      ║',
  '║                                                                    ║',
  '║  ─── COMMAND REFERENCE ───                                         ║',
  '║                                                                    ║',
  '║  INVESTIGATION:                                                    ║',
  '║    logs show --source=<src> [--search=<term>]  Security logs       ║',
  '║      Sources: email-gateway, firewall, auth, drive, dns, proxy     ║',
  '║    analyze <file>                    Examine file for IOCs          ║',
  '║    whois <domain>                    Domain registration lookup     ║',
  '║    nslookup <host>                   DNS resolution                ║',
  '║    connections [--user=<email>]      Active network sessions        ║',
  '║    scan network --target=<range>     Port/host scanning            ║',
  '║                                                                    ║',
  '║  RESPONSE:                                                         ║',
  '║    isolate <host>                    Network quarantine             ║',
  '║    revoke <user>                     Kill tokens, force reset       ║',
  '║    block <ip>                        Firewall deny rule             ║',
  '║                                                                    ║',
  '║  COMMUNICATION:                                                    ║',
  '║    report <finding>                  Log investigation finding      ║',
  '║    escalate                          Alert leadership               ║',
  '║                                                                    ║',
  '║  SYSTEM:                                                           ║',
  '║    help / help <command>             Command reference              ║',
  '║    status                            Mission progress               ║',
  '║    hint                              Get a hint                     ║',
  '║    clear                             Clear terminal                 ║',
  '║                                                                    ║',
  '║  ─── FIELD MISSIONS ───                                            ║',
  '║                                                                    ║',
  '║  After Tier 1 orientation, missions unlock progressively:          ║',
  '║                                                                    ║',
  '║  Op: Phishing Storm    ★☆☆  Financial sector phishing campaign    ║',
  '║  Op: Iron Lock         ★★☆  Hospital ransomware incident          ║',
  '║  Op: Glass House       ★★☆  Defense contractor insider threat     ║',
  '║  Op: Upstream          ★★★  Supply chain compromise               ║',
  '║  Op: Phantom Signal    ★★★  Government APT threat hunt            ║',
  '║  Op: Cloudfall         ★★★  Cloud infrastructure breach           ║',
  '║                                                                    ║',
  '║  Each mission has: briefing → investigation → decisions → debrief  ║',
  '║                                                                    ║',
  '║  ─── BEHAVIORAL DATA COLLECTION (INTERNAL) ───                     ║',
  '║                                                                    ║',
  '║  The game silently captures behavioral events for ML analysis.     ║',
  '║  The player is NEVER told about this. Key features collected:      ║',
  '║                                                                    ║',
  '║  • time_per_chapter      — Engagement / difficulty signal          ║',
  '║  • command_accuracy_rate  — First-try success on guided commands   ║',
  '║  • hint_request_frequency — Frustration threshold indicator        ║',
  '║  • quiz_score_per_chapter — Conceptual retention                   ║',
  '║  • scenario_command_order — Investigation methodology              ║',
  '║  • decision_response_time — Deliberation speed                     ║',
  '║  • decision_choice_vector — Risk tolerance, thoroughness pref      ║',
  '║  • chapter_skip_attempts  — Engagement / impatience signal         ║',
  '║  • free_command_explore   — Curiosity / experimentation tendency   ║',
  '║                                                                    ║',
  '║  All events stored in zustand store as BehavioralEvent[] with      ║',
  '║  missionId: \'noop\' (orientation) or mission ID (field ops).       ║',
  '║  Exportable as JSON for ML pipeline ingestion.                     ║',
  '║                                                                    ║',
  '║  ─── EVERY TRACKED DECISION POINT ───                              ║',
  '║                                                                    ║',
  '║  Each point below emits a BehavioralEvent with the option chosen,  ║',
  '║  time to respond, and whether the optimal answer was selected.     ║',
  '║  These are the primary features for the ML completion predictor.   ║',
  '║                                                                    ║',
  '║  ── CH01: THE DIGITAL BATTLEFIELD (9 quiz points) ──               ║',
  '║                                                                    ║',
  '║  Q1.1  CIA Classification: Hospital ransomware                     ║',
  '║        Correct: Availability. Tests: foundational concept grasp.   ║',
  '║        ML signal: Can observer distinguish C/I/A? Fundamental      ║',
  '║        prerequisite — failure here predicts dropout before Ch 3.   ║',
  '║                                                                    ║',
  '║  Q1.2  CIA Classification: Insider data theft                      ║',
  '║        Correct: Confidentiality. Tests: same concept, different    ║',
  '║        scenario. ML signal: consistency across similar questions.  ║',
  '║                                                                    ║',
  '║  Q1.3  CIA Classification: Bank account manipulation               ║',
  '║        Correct: Integrity. Tests: nuanced distinction (modify vs  ║',
  '║        steal). ML signal: precision in classification.             ║',
  '║                                                                    ║',
  '║  Q1.4  Threat Actor ID: Power utility SCADA persistence           ║',
  '║        Correct: Nation-state. Tests: pattern matching adversary    ║',
  '║        profiles. ML signal: can observer reason from indicators   ║',
  '║        to actor type? Strong predictor of investigation aptitude.  ║',
  '║                                                                    ║',
  '║  Q1.5  Threat Actor ID: Mass ransomware campaign                   ║',
  '║        Correct: Organized crime. Tests: volume/motive analysis.   ║',
  '║        ML signal: distinguishes financially-motivated from state.  ║',
  '║                                                                    ║',
  '║  Q1.6  Kill Chain: LinkedIn OSINT gathering                        ║',
  '║        Correct: Reconnaissance. Tests: kill chain phase mapping.   ║',
  '║        ML signal: sequential reasoning ability — key for          ║',
  '║        investigation methodology scoring.                          ║',
  '║                                                                    ║',
  '║  Q1.7  Kill Chain: Weaponized PDF delivery                         ║',
  '║        Correct: Delivery + Exploitation. Tests: multi-phase       ║',
  '║        recognition. ML signal: nuance in overlapping phases.      ║',
  '║                                                                    ║',
  '║  Q1.8  Kill Chain: Persistence + C2 + exfiltration                 ║',
  '║        Correct: Install + C2 + Actions. Tests: compound event     ║',
  '║        classification. ML signal: complexity handling capacity.    ║',
  '║                                                                    ║',
  '║  ── CH03: FIRST BLOOD (2 decision points) ──                       ║',
  '║                                                                    ║',
  '║  D3.1  Containment: Revoke tokens vs isolate vs monitor            ║',
  '║        Optimal: Revoke immediately. Tests: proportional response  ║',
  '║        under time pressure. ML signal: CRITICAL — measures        ║',
  '║        decision quality, risk tolerance, and action bias. Those   ║',
  '║        who choose "monitor" tend toward analysis paralysis.       ║',
  '║        Those who "isolate network" tend toward disproportionate   ║',
  '║        response. Highest-weight feature for completion prediction.║',
  '║                                                                    ║',
  '║  D3.2  Escalation: Legal+Director vs Director-only vs full IR      ║',
  '║        Optimal: Legal + Director. Tests: regulatory awareness,    ║',
  '║        communication instinct. ML signal: understanding that      ║',
  '║        technical incidents have organizational/legal dimensions.   ║',
  '║        Correlates strongly with Tier 2+ completion.               ║',
  '║                                                                    ║',
  '║  ── CH04: WALLS AND GATES (3 quiz points) ──                       ║',
  '║                                                                    ║',
  '║  Q4.1  Password storage: Identify MD5 hash vulnerability           ║',
  '║        Correct: MD5 unsalted. Tests: technical depth in crypto.   ║',
  '║        ML signal: distinguishing hash types = technical literacy. ║',
  '║                                                                    ║',
  '║  Q4.2  MFA bypass: Push bombing identification                     ║',
  '║        Correct: MFA fatigue. Tests: current threat awareness.     ║',
  '║        ML signal: familiarity with modern attack techniques.      ║',
  '║                                                                    ║',
  '║  Q4.3  Access control: Privilege creep diagnosis                   ║',
  '║        Correct: Permission accumulation. Tests: organizational    ║',
  '║        security understanding. ML signal: systematic vs          ║',
  '║        incident-focused thinking.                                  ║',
  '║                                                                    ║',
  '║  ── CH05: READING THE WIRE (1 quiz point) ──                       ║',
  '║                                                                    ║',
  '║  Q5.1  Attack sequence: Credential theft → lateral → DCSync       ║',
  '║        Correct: Full attack chain. Tests: multi-step attack       ║',
  '║        recognition from log fragments. ML signal: ability to      ║',
  '║        reconstruct attacker narrative from evidence — the core    ║',
  '║        investigation skill. High-weight feature.                   ║',
  '║                                                                    ║',
  '║  ── CH06: THE HUMAN FACTOR (2 quiz + 1 decision) ──                ║',
  '║                                                                    ║',
  '║  Q6.1  Phishing classification: 4 emails, identify the fake       ║',
  '║        Correct: Email with SPF fail + typosquat domain.           ║',
  '║        ML signal: visual pattern recognition in email headers.    ║',
  '║        Fast correct answers predict strong SOC aptitude.          ║',
  '║                                                                    ║',
  '║  Q6.2  Social engineering principles: Authority + urgency combo    ║',
  '║        ML signal: understanding psychological manipulation.       ║',
  '║                                                                    ║',
  '║  D6.1  BEC response: Training vs technical controls vs both        ║',
  '║        Optimal: Varies (decision step, no single correct).        ║',
  '║        ML signal: defense strategy preference — technical-first   ║',
  '║        vs people-first thinking. Neither is wrong; the balance    ║',
  '║        predicts career track (SOC vs GRC vs awareness).           ║',
  '║                                                                    ║',
  '║  ── CH07: WEB\'S SOFT UNDERBELLY (3 quiz points) ──                ║',
  '║                                                                    ║',
  '║  Q7.1  HTTP response analysis: Identify security concerns         ║',
  '║        ML signal: web technology literacy, header knowledge.      ║',
  '║                                                                    ║',
  '║  Q7.2  SQL injection: Evaluate dev\'s "fixed" claim                ║',
  '║        Correct: Client-side validation insufficient.              ║',
  '║        ML signal: understanding of defense-in-depth. Those who    ║',
  '║        accept client-side fixes tend to underestimate attackers.  ║',
  '║                                                                    ║',
  '║  Q7.3  XSS type identification: Stored XSS in comments            ║',
  '║        ML signal: web vulnerability classification skill.         ║',
  '║                                                                    ║',
  '║  ── CH08: BREACHING THE PERIMETER (2 quiz points) ──               ║',
  '║                                                                    ║',
  '║  Q8.1  Initial access vector: Macro-enabled doc via phishing       ║',
  '║        ML signal: kill chain mapping from realistic scenario.     ║',
  '║                                                                    ║',
  '║  Q8.2  Post-exploitation: Is the threat neutralized?               ║',
  '║        Correct: No — persistence mechanisms remain.               ║',
  '║        ML signal: CRITICAL — tests completeness of thinking.     ║',
  '║        Observers who say "yes, threat removed" tend to miss       ║',
  '║        persistence in real investigations. Strong predictor of    ║',
  '║        thoroughness dimension.                                     ║',
  '║                                                                    ║',
  '║  ── CH09: INVISIBLE ENEMIES (1 quiz + 1 decision) ──               ║',
  '║                                                                    ║',
  '║  Q9.1  Fileless malware: Identify memory-only attack indicators   ║',
  '║        ML signal: advanced threat recognition capability.         ║',
  '║                                                                    ║',
  '║  D9.1  Threat classification: APT vs insider vs false positive     ║',
  '║        ML signal: confidence calibration — how certain is the    ║',
  '║        observer before classifying? Response time here is key:   ║',
  '║        fast + correct = strong intuition. Slow + correct =       ║',
  '║        methodical. Fast + wrong = overconfidence risk factor.     ║',
  '║                                                                    ║',
  '║  ── CH10: CRYPTO WARS (3 quiz + 1 decision) ──                     ║',
  '║                                                                    ║',
  '║  Q10.1 Crypto primitive selection: Digital signature scenario       ║',
  '║        ML signal: applied cryptography understanding.             ║',
  '║                                                                    ║',
  '║  Q10.2 Key exchange: Diffie-Hellman identification                 ║',
  '║        ML signal: protocol-level knowledge depth.                 ║',
  '║                                                                    ║',
  '║  Q10.3 Crypto failure: Weak key management root cause              ║',
  '║        ML signal: can observer trace security failures to        ║',
  '║        operational (not just technical) causes?                    ║',
  '║                                                                    ║',
  '║  D10.1 Secrets management prioritization                           ║',
  '║        ML signal: prioritization under resource constraints.     ║',
  '║        Reveals whether observer thinks in risk/impact terms.     ║',
  '║                                                                    ║',
  '║  ── CH11: CLOUD FORTRESS (3 quiz + 1 decision) ──                  ║',
  '║                                                                    ║',
  '║  Q11.1 Shared responsibility: S3 bucket misconfiguration blame     ║',
  '║        ML signal: cloud operational model understanding.          ║',
  '║                                                                    ║',
  '║  Q11.2 SSRF to IMDS: What does the attack achieve?                 ║',
  '║        ML signal: cloud-specific attack chain reasoning.          ║',
  '║                                                                    ║',
  '║  Q11.3 Supply chain: Most effective preventive control             ║',
  '║        ML signal: DevSecOps maturity understanding.               ║',
  '║                                                                    ║',
  '║  D11.1 Zero trust migration: First-phase strategy                  ║',
  '║        ML signal: architectural thinking, ability to design       ║',
  '║        security programs (not just respond to incidents).         ║',
  '║        Predicts leadership/architecture career trajectory.        ║',
  '║                                                                    ║',
  '║  ── CH12: THE EDGE (2 quiz + 2 decision) ──                        ║',
  '║                                                                    ║',
  '║  Q12.1 AI-generated attack: Identify AI phishing vector            ║',
  '║        ML signal: awareness of emerging threat landscape.         ║',
  '║                                                                    ║',
  '║  D12.1 Ransomware: Pay vs don\'t pay (hospital scenario)           ║',
  '║        ML signal: CRITICAL — ethical reasoning under extreme     ║',
  '║        pressure. No correct answer. Choice reveals values:       ║',
  '║        "pay" = prioritizes immediate patient safety.              ║',
  '║        "don\'t pay" = prioritizes long-term deterrence.           ║',
  '║        Response time is the most informative feature here:       ║',
  '║        fast decisions indicate pre-formed ethical framework.      ║',
  '║        Slow decisions indicate genuine moral deliberation.        ║',
  '║        Both are valuable — different roles need different types.  ║',
  '║                                                                    ║',
  '║  Q12.2 Supply chain response: Appropriate timeline                  ║',
  '║        ML signal: incident response procedural knowledge.         ║',
  '║                                                                    ║',
  '║  D12.2 NorthGrid strategic security: Highest-impact initiative     ║',
  '║        ML signal: GRADUATION EXERCISE — synthesis of entire      ║',
  '║        12-chapter curriculum. Tests strategic thinking, not       ║',
  '║        tactical response. Choice pattern correlates with:        ║',
  '║        • Identity-first → Security Architect track                ║',
  '║        • Detection-first → SOC/Threat Hunter track                ║',
  '║        • Network-first → Infrastructure Security track            ║',
  '║        This is the single most predictive feature for career     ║',
  '║        path alignment in the assessment report.                   ║',
  '║                                                                    ║',
  '║  ── MISSION: PHISHING STORM (3 decision points) ──                 ║',
  '║                                                                    ║',
  '║  DM.1  Initial response: Revoke vs monitor vs isolate network      ║',
  '║        Optimal: Revoke immediately. Same pattern as D3.1 but     ║',
  '║        in a real mission with more evidence and time pressure.   ║',
  '║        ML signal: does the observer\'s decision quality improve   ║',
  '║        from orientation (D3.1) to mission (DM.1)? Improvement   ║',
  '║        = learning effect. No change = reinforcement needed.      ║',
  '║        This delta is a key completion predictor.                  ║',
  '║                                                                    ║',
  '║  DM.2  Escalation timing: Legal+CISO vs CISO-only vs full IR      ║',
  '║        Optimal: Legal + CISO (M&A data = securities violation).  ║',
  '║        ML signal: regulatory awareness transfer from Ch03 D3.2.  ║',
  '║        Tests whether orientation concepts apply under pressure.  ║',
  '║                                                                    ║',
  '║  DM.3  Remediation: MFA+OAuth review vs block IPs vs training      ║',
  '║        Optimal: MFA + OAuth review (systemic fix).               ║',
  '║        ML signal: root-cause thinking vs symptom treatment.      ║',
  '║        Observers who choose "block IPs" focus on the immediate   ║',
  '║        attacker. Those who choose "MFA" fix the vulnerability.   ║',
  '║        This distinction predicts Tier 2+ performance.            ║',
  '║                                                                    ║',
  '║  ── AGGREGATE ML FEATURES ──                                       ║',
  '║                                                                    ║',
  '║  Total tracked decision/quiz points: 34                            ║',
  '║  Of which: 25 quizzes (correct/incorrect), 9 decisions (choice)   ║',
  '║                                                                    ║',
  '║  Highest-weight completion predictors (ranked):                    ║',
  '║    1. D3.1 containment decision (orientation, first real choice)  ║',
  '║    2. D3.1→DM.1 improvement delta (learning effect)              ║',
  '║    3. Ch01 quiz accuracy (foundational concept retention)         ║',
  '║    4. Q5.1 attack chain reconstruction (investigation aptitude)   ║',
  '║    5. Q8.2 persistence check (thoroughness indicator)             ║',
  '║    6. command_accuracy_rate across all guided commands             ║',
  '║    7. time_per_chapter trend (accelerating = engaged)             ║',
  '║    8. D12.1 ransomware response time (ethical framework signal)   ║',
  '║    9. D12.2 graduation exercise choice (career path signal)       ║',
  '║   10. hint_request_frequency (frustration threshold)              ║',
  '║                                                                    ║',
  '║  Recommended model: gradient-boosted classifier (XGBoost) on     ║',
  '║  the feature vector [quiz_accuracy_pct, decision_optimal_pct,     ║',
  '║  avg_response_time_ms, d3_1_choice, d3_dm_delta, ch01_score,     ║',
  '║  q5_1_correct, q8_2_correct, hint_frequency, time_trend_slope]   ║',
  '║  Target: binary (completed_all_12_chapters / dropped_out)         ║',
  '║                                                                    ║',
  '║  ─── TESTING GUIDE ───                                             ║',
  '║                                                                    ║',
  '║  ADMIN MODE: On the title screen, press ] three times.             ║',
  '║  A red [ADMIN MODE ACTIVE] indicator appears.                      ║',
  '║                                                                    ║',
  '║  Admin shortcuts:                                                  ║',
  '║    Orientation:  SPACE skips any step instantly                     ║',
  '║    Missions:     SPACE auto-picks optimal decision                 ║',
  '║    Missions:     Type "admin-skip" to discover evidence            ║',
  '║    Global:       Text speed set to instant                         ║',
  '║                                                                    ║',
  '║  Testing checklist:                                                ║',
  '║    [ ] Title screen: glitch assemble animation on figure           ║',
  '║    [ ] Title screen: gradient block OMNIUS logo renders            ║',
  '║    [ ] Title screen: animated eyes blink and look around           ║',
  '║    [ ] Title screen: menu options highlight with bracket box       ║',
  '║    [ ] About DI7: classified briefing page renders, scrollable     ║',
  '║    [ ] New Operation: orientation chapter select appears            ║',
  '║    [ ] Chapter 1 unlocked, chapters 2-12 locked                    ║',
  '║    [ ] Complete Ch 1 → Ch 2 unlocks                                ║',
  '║    [ ] Ch 1-3 complete → Hub screen with missions                  ║',
  '║    [ ] Hub: mission list with difficulty stars                     ║',
  '║    [ ] Mission: briefing → terminal → commands → decisions         ║',
  '║    [ ] Mission: debrief shows operational assessment               ║',
  '║    [ ] All 12 chapters playable end-to-end                         ║',
  '║    [ ] Ch 12 complete → R1 clearance granted                       ║',
  '║    [ ] Admin mode: ] ] ] toggles on/off                            ║',
  '║    [ ] Admin: Space skips orientation steps                        ║',
  '║    [ ] Admin: Space auto-picks mission decisions                   ║',
  '║    [ ] Report screen: no mention of "aptitude" to player           ║',
  '║    [ ] All text says "Observer" never "Analyst"                    ║',
  '║    [ ] All text says "DI7" never "Panopticon"                     ║',
  '║                                                                    ║',
  '║  ─── TECH STACK ───                                                ║',
  '║                                                                    ║',
  '║  Runtime:    Node.js 20+ / TypeScript 6                            ║',
  '║  Terminal:   Ink 5 (React for CLI) + chalk + cli-spinners          ║',
  '║  State:      zustand + immer                                       ║',
  '║  Build:      tsup → single ESM bundle                              ║',
  '║  Test:       vitest                                                ║',
  '║  Distribute: npm / npx omnius                                      ║',
  '║                                                                    ║',
  '║  Source material:                                                  ║',
  '║    · Security Engineering 3e — Ross Anderson (Wiley, 2020)         ║',
  '║    · The Hacker Playbook 3 — Peter Kim (Secure Planet, 2018)       ║',
  '║    · Web App Hacker\'s Handbook — Stuttard & Pinto (Wiley, 2008)    ║',
  '║                                                                    ║',
  '║  ─── CREDITS ───                                                   ║',
  '║                                                                    ║',
  '║  Created by Shiv Garge · Garge Studio                              ║',
  '║  Powered by OMNIUS v4.2.1                                          ║',
  '║                                                                    ║',
  '╚══════════════════════════════════════════════════════════════════════╝',
];

export function GuideScreen() {
  const setScreen = useGameStore((s) => s.setScreen);
  const [scrollOffset, setScrollOffset] = useState(0);

  const visibleLines = 35;
  const maxScroll = Math.max(0, GUIDE_LINES.length - visibleLines);

  useInput((_input, key) => {
    if (key.return || key.escape) {
      setScreen('hub');
    }
    if (key.upArrow) {
      setScrollOffset((s) => Math.max(0, s - 1));
    }
    if (key.downArrow) {
      setScrollOffset((s) => Math.min(maxScroll, s + 1));
    }
    // Page up/down
    if (_input === ' ') {
      setScrollOffset((s) => Math.min(maxScroll, s + 10));
    }
  });

  return (
    <Box flexDirection="column" paddingX={2} paddingY={1}>
      <Box flexDirection="column">
        {GUIDE_LINES.slice(scrollOffset, scrollOffset + visibleLines).map((line, i) => {
          const isBorder = line.includes('╔') || line.includes('╚') || line.includes('╠');
          const isHeader = line.includes('───');
          return (
            <Text
              key={i}
              color={isBorder ? colors.omnius : isHeader ? colors.cyan : colors.dim}
              bold={isHeader}
            >
              {line}
            </Text>
          );
        })}
      </Box>

      <Box marginTop={1} justifyContent="space-between">
        <Text color={colors.dim}>
          ↑↓ Scroll · Space PageDown · {scrollOffset > 0 ? '▲' : ' '}{scrollOffset < maxScroll ? '▼' : ' '}
          {' '}({scrollOffset + 1}-{Math.min(scrollOffset + visibleLines, GUIDE_LINES.length)}/{GUIDE_LINES.length})
        </Text>
        <Text color={colors.dim}>
          <Text color={colors.cyan} bold>ESC</Text> / <Text color={colors.cyan} bold>ENTER</Text> to return
        </Text>
      </Box>
    </Box>
  );
}
